-- Nhập danh sách Use Case dự án GPDN_DNMB_EVNNPC_QTVT_251004 - phần Web
-- Nguồn: Danh sách chức năng điều chỉnh BCC Vật tư_0508.xlsx (sheet UC sau điều chỉnh final)
-- Gồm 8 module/nhóm (kind = group) và 37 use case (kind = usecase), cây tối đa 3 cấp.
-- Sinh tự động bởi scripts/gen-usecase-import.py - đừng sửa tay, hãy sửa Excel rồi sinh lại.
--
-- Chạy SAU migration 0009_usecase_attributes.sql, trong Supabase SQL Editor.
-- An toàn khi chạy lại: khớp theo (dự án, mã); chỉ cập nhật tên/tác nhân/luồng/nhãn/độ phức tạp/transaction,
-- KHÔNG ghi đè trạng thái, tiến độ, người phụ trách, mô tả hay tiêu chí nghiệm thu đã nhập tay.
-- Hoàn tác: chạy qtvt_usecases_rollback.sql.

do $import$
declare
  v_project_code constant text := 'GPDN_DNMB_EVNNPC_QTVT_251004';
  v_project uuid;
  r record;
  v_parent uuid;
  v_new boolean;
  n_new integer := 0;
  n_upd integer := 0;
begin
  select id into v_project from public.projects where code = v_project_code;
  if v_project is null then
    raise exception 'Không tìm thấy dự án có mã %. Kiểm tra lại mã dự án.', v_project_code;
  end if;

  for r in
    select *
      from jsonb_to_recordset($json$[{"sort":1,"code":"W-I","parent":null,"kind":"group","title":"Quản lý định danh vật tư, thiết bị","actor":"","flow":[],"tags":["Web"],"complexity":null,"transactions":null,"necessity":"B"},
{"sort":2,"code":"W-I.1","parent":"W-I","kind":"group","title":"Cấu hình thông số định danh vật tư, thiết bị","actor":"","flow":[],"tags":["Web"],"complexity":null,"transactions":null,"necessity":"B"},
{"sort":3,"code":"UC-001","parent":"W-I.1","kind":"usecase","title":"Quản lý cấu hình danh sách chủng loại VT, TB cần định danh","actor":"Quản trị phần mềm","flow":["1. Quản trị phần mềm thêm mới cấu hình danh sách chủng loại VT, TB cần định danh trên giao diện. Hệ thống lưu cấu hình danh sách chủng loại VT, TB cần định danh được thêm mới","2. Quản trị phần mềm thực hiện chỉnh sửa cấu hình danh sách chủng loại VT, TB cần định danh. Hệ thống lưu cấu hình danh sách chủng loại VT, TB cần định danh do người dùng chỉnh sửa","3. Quản trị phần mềm thực hiện chọn và xóa một hoặc một số cấu hình danh sách chủng loại VT, TB cần định danh. Hệ thống kiểm tra điều kiện ràng buộc và xóa thông tin theo yêu cầu người dùng","4. Quản trị phần mềm tìm kiếm cấu hình danh sách chủng loại VT, TB cần định danh. Hệ thống tìm kiếm và trả kết quả cho người dùng","5. Quản trị phần mềm xem chi tiếtcấu hình danh sách chủng loại VT, TB cần định danh. Hệ thống hiển thị chi tiết cấu hình danh sách chủng loại VT, TB cần định danh"],"tags":["Web"],"complexity":"medium","transactions":5,"necessity":"B"},
{"sort":4,"code":"UC-002","parent":"W-I.1","kind":"usecase","title":"Cấu hình dải số định danh vật tư thiết bị","actor":"Hệ thống","flow":["1. Hệ thống tự động sinh dải số định danh cho vật tư thiết bị theo quy tắc"],"tags":["Web"],"complexity":"simple","transactions":1,"necessity":"B"},
{"sort":5,"code":"UC-003","parent":"W-I.1","kind":"usecase","title":"Quản lý cấu hình khuôn in mã QR","actor":"Quản trị phần mềm","flow":["1. Quản trị phần mềm thêm mới cấu hình khuôn in mã QR trên giao diện. Hệ thống lưu cấu hình khuôn in mã QR được thêm mới","2. Quản trị phần mềm thực hiện chỉnh sửa cấu hình khuôn in mã QR. Hệ thống lưu cấu hình khuôn in mã QR do người dùng chỉnh sửa","3. Quản trị phần mềm thực hiện chọn và xóa một hoặc một số cấu hình khuôn in mã QR. Hệ thống kiểm tra điều kiện ràng buộc và xóa thông tin theo yêu cầu người dùng","4. Quản trị phần mềm tìm kiếm cấu hình khuôn in mã QR. Hệ thống tìm kiếm và trả kết quả cho người dùng","5. Quản trị phần mềm xem chi tiết cấu hình khuôn in mã QR. Hệ thống hiển thị chi tiết cấu hình khuôn in mã QR"],"tags":["Web"],"complexity":"medium","transactions":5,"necessity":"B"},
{"sort":6,"code":"W-I.2","parent":"W-I","kind":"group","title":"Quản lý kế hoạch định danh","actor":"","flow":[],"tags":["Web"],"complexity":null,"transactions":null,"necessity":"B"},
{"sort":7,"code":"UC-004","parent":"W-I.2","kind":"usecase","title":"Khai báo thông số kỹ thuật","actor":"Người dùng","flow":["1. Người dùng thêm mới thông số kỹ thuật trên giao diện. Hệ thống lưu thông số kỹ thuật được thêm mới","2. Người dùng thực hiện chỉnh sửa thông số kỹ thuật. Hệ thống lưu thông số kỹ thuật do người dùng chỉnh sửa","3. Người dùng xem chi tiết thông số kỹ thuật. Hệ thống hiển thị chi tiết thông số kỹ thuật"],"tags":["Web"],"complexity":"simple","transactions":3,"necessity":"B"},
{"sort":8,"code":"UC-005","parent":"W-I.2","kind":"usecase","title":"Quản lý kế hoạch định danh theo hợp đồng","actor":"Người dùng","flow":["1. Người dùng thêm mới kế hoạch định danh theo hợp đồng trên giao diện. Hệ thống lưu kế hoạch định danh theo hợp đồng được thêm mới","2. Người dùng thực hiện chỉnh sửa kế hoạch định danh theo hợp đồng. Hệ thống lưu kế hoạch định danh theo hợp đồng do người dùng chỉnh sửa","3. Người dùng thực hiện chọn và xóa một hoặc một số kế hoạch định danh theo hợp đồng. Hệ thống kiểm tra điều kiện ràng buộc và xóa thông tin theo yêu cầu người dùng","4. Người dùng tìm kiếm kế hoạch định danh theo hợp đồng. Hệ thống tìm kiếm và trả kết quả cho người dùng","5. Người dùng xem chi tiết kế hoạch định danh theo hợp đồng. Hệ thống hiển thị chi tiết kế hoạch định danh theo hợp đồng","6. Người dùng gửi danh sách mã định danh xuống cho đơn vị thực hiện kế hoạch"],"tags":["Web"],"complexity":"medium","transactions":6,"necessity":"B"},
{"sort":9,"code":"UC-006","parent":"W-I.2","kind":"usecase","title":"Nhập kế hoạch định danh theo hợp đồng theo file excel","actor":"Người dùng","flow":["1. Người dùng chọn tải file mẫu từ hệ thống về máy tính và thực hiện nhập thông tin vào file","2. Người dùng tải file vừa nhập vào hệ thống. Hệ thống kiểm tra tính hợp lệ của dữ liệu và lưu thông tin vào CSDL","3. Người dùng xem chi tiết hoạch định danh theo hợp đồng theo file excel được import thành công"],"tags":["Web"],"complexity":"simple","transactions":3,"necessity":"B"},
{"sort":10,"code":"UC-007","parent":"W-I.2","kind":"usecase","title":"Quản lý kế hoạch định danh vật tư, thiết bị tồn kho","actor":"Người dùng","flow":["1. Người dùng thêm mới kế hoạch định danh vật tư, thiết bị tồn kho trên giao diện. Hệ thống lưu kế hoạch định danh vật tư, thiết bị tồn kho được thêm mới","2. Người dùng thực hiện chỉnh sửa kế hoạch định danh vật tư, thiết bị tồn kho. Hệ thống lưu kế hoạch định danh vật tư, thiết bị tồn kho do người dùng chỉnh sửa","3. Người dùng thực hiện chọn và xóa một hoặc một số kế hoạch định danh vật tư, thiết bị tồn kho. Hệ thống kiểm tra điều kiện ràng buộc và xóa thông tin theo yêu cầu người dùng","4. Người dùng tìm kiếm kế hoạch định danh vật tư, thiết bị tồn kho. Hệ thống tìm kiếm và trả kết quả cho người dùng","5. Người dùng xem chi tiếtkế hoạch định danh vật tư, thiết bị tồn kho. Hệ thống hiển thị chi tiết kế hoạch định danh vật tư, thiết bị tồn kho","6. Người dùng gửi danh sách mã định danh xuống cho đơn vị thực hiện kế hoạch"],"tags":["Web"],"complexity":"medium","transactions":6,"necessity":"B"},
{"sort":11,"code":"UC-008","parent":"W-I.2","kind":"usecase","title":"Nhập kế hoạch định danh vật tư, thiết bị tồn kho theo file excel","actor":"Người dùng","flow":["1. Người dùng chọn tải file mẫu từ hệ thống về máy tính và thực hiện nhập thông tin vào file","2. Người dùng tải file vừa nhập vào hệ thống. Hệ thống kiểm tra tính hợp lệ của dữ liệu và lưu thông tin vào CSDL","3. Người dùng xem chi tiết hoạch định danh vật tư, thiết bị tồn kho theo file excel được import thành công"],"tags":["Web"],"complexity":"simple","transactions":3,"necessity":"B"},
{"sort":12,"code":"UC-009","parent":"W-I.2","kind":"usecase","title":"Quản lý kế hoạch định danh vật tư, thiết bị trên lưới","actor":"Người dùng","flow":["1. Người dùng thêm mới kế hoạch định danh vật tư, thiết bị trên lưới trên giao diện. Hệ thống lưu kế hoạch định danh vật tư, thiết bị trên lưới được thêm mới","2. Người dùng thực hiện chỉnh sửa kế hoạch định danh vật tư, thiết bị trên lưới. Hệ thống lưu kế hoạch định danh vật tư, thiết bị trên lưới do người dùng chỉnh sửa","3. Người dùng thực hiện chọn và xóa một hoặc một số kế hoạch định danh vật tư, thiết bị trên lưới. Hệ thống kiểm tra điều kiện ràng buộc và xóa thông tin theo yêu cầu người dùng","4. Người dùng tìm kiếm kế hoạch định danh vật tư, thiết bị trên lưới. Hệ thống tìm kiếm và trả kết quả cho người dùng","5. Người dùng xem chi tiếtkế hoạch định danh vật tư, thiết bị trên lưới. Hệ thống hiển thị chi tiết kế hoạch định danh vật tư, thiết bị trên lưới","6. Người dùng gửi danh sách mã định danh xuống cho đơn vị thực hiện kế hoạch"],"tags":["Web"],"complexity":"medium","transactions":6,"necessity":"B"},
{"sort":13,"code":"UC-010","parent":"W-I.2","kind":"usecase","title":"Nhập kế hoạch định danh vật tư, thiết bị trên lưới theo file excel","actor":"Người dùng","flow":["1. Người dùng chọn tải file mẫu từ hệ thống về máy tính và thực hiện nhập thông tin vào file","2. Người dùng tải file vừa nhập vào hệ thống. Hệ thống kiểm tra tính hợp lệ của dữ liệu và lưu thông tin vào CSDL","3. Người dùng xem chi tiết hoạch định danh vật tư, thiết bị trên lưới theo file excel được import thành công"],"tags":["Web"],"complexity":"simple","transactions":3,"necessity":"B"},
{"sort":14,"code":"W-I.3","parent":"W-I","kind":"group","title":"Quản lý định danh","actor":"","flow":[],"tags":["Web"],"complexity":null,"transactions":null,"necessity":"B"},
{"sort":15,"code":"UC-011","parent":"W-I.3","kind":"usecase","title":"Quản lý danh sách mã định danh","actor":"Người dùng","flow":["1. Người dùng tạo mới danh sách mã định danh trên giao diện. Hệ thống tạo mã định danh và + Đối với Vật tư, thiết bị sử dụng QR Code, hệ thống tạo mã QR Code theo mã định danh vừa tạo + Đối với Vật tư, thiết bị sử dụng RFID, hệ thống ghi dữ liệu vào thẻ RFID theo mã định danh vừa tạo","2. Người dùng thực hiện chọn và xóa một hoặc một số danh sách mã định danh. Hệ thống kiểm tra điều kiện ràng buộc và xóa mã định danh theo yêu cầu của người dùng.","3. Người dùng tìm kiếm danh sách mã định danh. Hệ thống tìm kiếm và trả kết quả cho người dùng","4. Người dùng xem chi tiết danh sách mã định danh. Hệ thống hiển thị chi tiết danh sách mã định danh tương ứng","5. Người dùng xem danh sách mã định danh có phân trang. Hệ thống chuyển trang theo yêu cầu của người dùng"],"tags":["Web"],"complexity":"medium","transactions":5,"necessity":"B"},
{"sort":16,"code":"UC-012","parent":"W-I.3","kind":"usecase","title":"Tích hợp với máy in để in QR Code","actor":"Hệ thống","flow":["1. Người dùng chọn loại máy in QR Code để kết nối và nhập thông số kết nối. Hệ thống gửi yêu cầu kết nối đến máy in","2. Máy in phản hồi về trạng thái kết nối. Hệ thống hiển thị trạng thái kết nối."],"tags":["Web"],"complexity":"simple","transactions":2,"necessity":"B"},
{"sort":17,"code":"UC-013","parent":"W-I.3","kind":"usecase","title":"In QR cho mã định danh","actor":"Người dùng","flow":["1. Người dùng tìm kiếm danh sách mã định danh muốn in QR. Hệ thống tìm kiếm và hiển thị danh sách mã định danh cho người dùng.","2. Người dùng xem trước QR Code trước khi in. Hệ thống hiển thị bản xem trước của QR Code","3. Người dùng thực hiện in mã định danh. Hệ thống in mã định danh theo yêu cầu"],"tags":["Web"],"complexity":"simple","transactions":3,"necessity":"B"},
{"sort":18,"code":"UC-014","parent":"W-I.3","kind":"usecase","title":"Cập nhật serial number","actor":"Người dùng","flow":["1. Người dùng tìm kiếm danh sách mã định danh để gán serial number. Hệ thống hiển thị danh sách mã định danh theo điều kiện tìm kiếm","2. Người dùng nhập serial number theo từng mã định danh. Hệ thống lưu kết quả do Người dùng nhập và cập nhật trạng thái đã dán QR Code đối với VTTB được quản lý bằng QR Code hoặc trạng thái đã gắn thẻ RFID đối với VTTB được quản lý bằng RFID.","3. Người dùng chỉnh sửa serial number đã nhập. Hệ thống lưu kết quả chỉnh sửa cho Người dùng nhập","4. Người dùng tìm kiếm mã serial number đã nhập. Hệ thống hiển thị kết quả tìm kiếm theo yêu cầu của Người dùng","5. Người dùng xóa mã serial number đã nhập. Hệ thống xóa serial number theo yêu cầu của Người dùng.","6. Người dùng xem chi tiết mã serial number đã nhập. Hệ thống hiển thị thông tin chi tiết mã serial number"],"tags":["Web"],"complexity":"medium","transactions":6,"necessity":"B"},
{"sort":19,"code":"UC-015","parent":"W-I.3","kind":"usecase","title":"Map mã định danh giữa các phần mềm","actor":"Người dùng","flow":["1. Người dùng tìm kiếm danh sách mã định danh để mapping giữa các phần mềm. Hệ thống hiển thị danh sách mã định danh theo điều kiện tìm kiếm","2. Người dùng mapping mã định danh trên hệ thống với mã của VTTB trên hệ thống CMIS, PMIS, QLMBA. Hệ thống lưu kết quả do Người dùng nhập.","3. Người dùng chỉnh sửa kết quả mapping mã định danh giữa các phần mềm đã thực hiện. Hệ thống lưu kết quả chỉnh sửa cho Người dùng nhập","4. Người dùng xóa kết quả mapping. Hệ thống xóa kết quả mapping theo yêu cầu của Người dùng.","5. Người dùng xem chi tiết kết quả mapping mã định danh giữa các phần mềm. Hệ thống hiển thị thông tin chi tiết kết quả mapping","6. Người dùng tìm kiếm kết quả mapping giữa các hệ thống. Hệ thống hiển thị kết quả tìm kiếm theo yêu cầu của Người dùng","7. Người dùng xem danh sách mapping giữa các hệ thống có phân trang. Hệ thống chuyển trang theo yêu cầu."],"tags":["Web"],"complexity":"medium","transactions":7,"necessity":"B"},
{"sort":20,"code":"UC-016","parent":"W-I.3","kind":"usecase","title":"Import mapping mã định danh giữa các phần mềm","actor":"Người dùng","flow":["1. Người dùng chọn tải file mẫu từ hệ thống về máy tính và thực hiện nhập thông tin vào file","2. Người dùng tải file vừa nhập vào hệ thống. Hệ thống kiểm tra tính hợp lệ của dữ liệu và lưu thông tin vào CSDL","3. Người dùng xem chi tiết mapping mã định danh giữa các phần mềm được import thành công"],"tags":["Web"],"complexity":"simple","transactions":3,"necessity":"B"},
{"sort":21,"code":"W-I.4","parent":"W-I","kind":"group","title":"Quản lý giao dịch nhập xuất chi tiết theo mã định danh","actor":"","flow":[],"tags":["Web"],"complexity":null,"transactions":null,"necessity":"B"},
{"sort":22,"code":"UC-017","parent":"W-I.4","kind":"usecase","title":"Quản lý giao dịch nhập/ xuất chi tiết theo mã định danh","actor":"Người dùng","flow":["1. Người dùng nhập điều kiện tìm kiếm giao dịch nhập xuất chi tiết. Hệ thống thực hiện truy vấn thông tin trong CSDL và hiển thị danh sách giao dịch nhập xuất.","2. Người dùng Xem chi tiết giao dịch nhập xuất chi tiết. Hệ thống hiển thị chi tiết thông tin giao dịch nhập xuất chi tiết","3. Người dùng thực hiện nhập mã định danh cho VTTB trong giao dịch nhập xuất. Hệ thống lưu thông tin do Người dùng nhập.","4. Người dùng thực hiện chỉnh sửa mã định danh cho VTTTB trong giao dịch nhập xuất. Hệ thống lưu thông tin do Người dùng chỉnh sửa","5. Người dùng thực hiện xem chi tiết mã định danh cho VTTB trong giao dịch nhập, xuất. Hệ thống hiển thị thông tin chi tiết cho người dùng.","6. Người dùng xóa mã định danh cho VTTB trong giao dịch nhập xuất. Hệ thống thực hiện xóa theo yêu cầu người dùng","7. Người dùng tìm kiếm mã định danh của VTTB trong giao dịch nhập xuất. Hệ thống tìm kiếm và hiển thị thông tin cho Người dùng."],"tags":["Web"],"complexity":"medium","transactions":7,"necessity":"B"},
{"sort":23,"code":"UC-018","parent":"W-I.4","kind":"usecase","title":"Nhập xuất chi tiết bằng mã QR","actor":"Người dùng","flow":["1. Người dùng quét mã QR trên VTTB cần nhập/xuất kho. Máy quét mã vạch thực hiện quét mã và gửi dữ liệu đến hệ thống.","2. Hệ thống nhận dữ liệu và kiểm tra thông tin và hiển thị thông tin chi tiết cho Người dùng. Người dùng xem chi tiết thông tin và xác nhận VTTB cần nhập/ xuất kho.","3. Hệ thống lưu thông tin do Người dùng xác nhận trong CSDL và hiển thị kết quả nhập/xuất kho cho Người dùng. Người dùng xem thông tin kết quả nhập/ xuất kho.","4. Hệ thống lưu lại lịch sử nhập/ xuất kho"],"tags":["Web"],"complexity":"medium","transactions":4,"necessity":"B"},
{"sort":24,"code":"W-II","parent":null,"kind":"group","title":"Đánh giá chất lượng nhà cung cấp, nhà sản xuất","actor":"","flow":[],"tags":["Web"],"complexity":null,"transactions":null,"necessity":"B"},
{"sort":25,"code":"UC-019","parent":"W-II","kind":"usecase","title":"Quản lý tiêu chí đánh giá chất lượng nhà cung cấp, nhà sản xuất","actor":"Người dùng","flow":["1. Người dùng thêm mới tiêu chí đánh giá chất lượng nhà cung cấp, nhà sản xuất. Hệ thống lưu tiêu chí đánh giá được thêm mới.","2. Người dùng thực hiện chỉnh sửa tiêu chí đánh giá chất lượng nhà cung cấp, nhà sản xuất theo biểu mẫu. Hệ thống lưu thông tin tiêu chí đánh giá chất lượng nhà cung cấp, nhà sản xuất vừa chỉnh sửa","3. Người dùng xóa tiêu chí đánh giá chất lượng nhà cung cấp, nhà sản xuất. Hệ thống xóa tiêu chí đánh giá chất lượng nhà cung cấp, nhà sản xuất theo yêu cầu.","4. Người dùng gửi phê duyệt tiêu chí đánh giá chất lượng nhà cung cấp, nhà sản xuất. Hệ thống gửi phê duyệt theo yêu cầu","5. Lãnh đạo phê duyệt tiêu chí đánh giá chất lượng nhà cung cấp, nhà sản xuất. Hệ thống lưu kết quả phê duyệt","6. Người dùng tìm kiếm tiêu chí đánh giá chất lượng nhà cung cấp, nhà sản xuất. Hệ thống tìm kiếm và trả kết quả cho người dùng","7. Người dùng xem tiêu chí đánh giá chất lượng nhà cung cấp, nhà sản xuất. Hệ thống hiển thị thông tin chi tiết theo yêu cầu"],"tags":["Web"],"complexity":"medium","transactions":7,"necessity":"B"},
{"sort":26,"code":"UC-020","parent":"W-II","kind":"usecase","title":"Báo cáo theo dõi tổng sự cố của VTTB","actor":"Người dùng","flow":["1. Người dùng xem Báo cáo theo dõi tổng sự cố của VTTB . Hệ thống hiển thị thông tin chi tiết Báo cáo theo dõi tổng sự cố của VTTB","2. Người dùng nhập các tiêu chí lọc về theo dõi tổng sự cố của VTTB . Hệ thống truy vấn thông tin trong CSDL và hiển thị kết quả Báo cáo theo dõi tổng sự cố của VTTB theo tiêu chí lọc"],"tags":["Web"],"complexity":"simple","transactions":2,"necessity":"B"},
{"sort":27,"code":"UC-021","parent":"W-II","kind":"usecase","title":"Báo cáo theo dõi tỷ lệ sự cố của VTTB theo nhà sản xuất","actor":"Người dùng","flow":["1. Người dùng xem Báo cáo theo dõi tỷ lệ sự cố của VTTB theo nhà sản xuất. Hệ thống hiển thị thông tin chi tiết Báo cáo theo dõi tỷ lệ sự cố của VTTB theo nhà sản xuất","2. Người dùng nhập các tiêu chí lọc về theo dõi tỷ lệ sự cố của VTTB theo nhà sản xuất. Hệ thống truy vấn thông tin trong CSDL và hiển thị kết quả Báo cáo theo dõi tỷ lệ sự cố của VTTB theo nhà sản xuất theo tiêu chí lọc"],"tags":["Web"],"complexity":"simple","transactions":2,"necessity":"B"},
{"sort":28,"code":"UC-022","parent":"W-II","kind":"usecase","title":"Báo cáo theo dõi tỷ lệ sự cố của VTTB theo nhà cung cấp","actor":"Người dùng","flow":["1. Người dùng xem Báo cáo theo dõi tỷ lệ sự cố của VTTB theo nhà cung cấp. Hệ thống hiển thị thông tin chi tiết Báo cáo theo dõi tỷ lệ sự cố của VTTB theo nhà cung cấp","2. Người dùng nhập các tiêu chí lọc về theo dõi tỷ lệ sự cố của VTTB theo nhà cung cấp. Hệ thống truy vấn thông tin trong CSDL và hiển thị kết quả Báo cáo theo dõi tỷ lệ sự cố của VTTB theo nhà cung cấp theo tiêu chí lọc"],"tags":["Web"],"complexity":"simple","transactions":2,"necessity":"B"},
{"sort":29,"code":"UC-023","parent":"W-II","kind":"usecase","title":"Báo cáo theo dõi tỷ lệ sự cố chủng loại VTTB theo nguyên nhân gây ra sự cố","actor":"Người dùng","flow":["1. Người dùng xem Báo cáo theo dõi tỷ lệ sự cố chủng loại VTTB theo nguyên nhân gây ra sự cố. Hệ thống hiển thị thông tin chi tiết Báo cáo theo dõi tỷ lệ sự cố chủng loại VTTB theo nguyên nhân gây ra sự cố","2. Người dùng nhập các tiêu chí lọc về theo dõi tỷ lệ sự cố chủng loại VTTB theo nguyên nhân gây ra sự cố. Hệ thống truy vấn thông tin trong CSDL và hiển thị kết quả Báo cáo theo dõi tỷ lệ sự cố chủng loại VTTB theo nguyên nhân gây ra sự cố theo tiêu chí lọc"],"tags":["Web"],"complexity":"simple","transactions":2,"necessity":"B"},
{"sort":30,"code":"W-III","parent":null,"kind":"group","title":"Hồ sơ vật tư, thiết bị","actor":"","flow":[],"tags":["Web"],"complexity":null,"transactions":null,"necessity":"B"},
{"sort":31,"code":"UC-024","parent":"W-III","kind":"usecase","title":"Tìm kiếm và xem danh sách hồ sơ vật tư, thiết bị","actor":"Người dùng","flow":["1. Người dùng tìm kiếm và xem danh sách hồ sơ vật tư, thiết bị. Hệ thống hiển thị danh sách hồ sơ vật tư thiết bị theo điều kiện tìm kiếm"],"tags":["Web"],"complexity":"simple","transactions":1,"necessity":"B"},
{"sort":32,"code":"UC-025","parent":"W-III","kind":"usecase","title":"Chỉnh sửa thông tin Hồ sơ vật tư, thiết bị","actor":"Người dùng","flow":["1. Người dùng chỉnh sửa thông tin một vật tư, thiết bị. Hệ thống lưu thông tin chỉnh sửa của vật tư, thiết bị"],"tags":["Web"],"complexity":"simple","transactions":1,"necessity":"B"},
{"sort":33,"code":"UC-026","parent":"W-III","kind":"usecase","title":"Xem thông tin Hồ sơ vật tư, thiết bị - thông tin chung","actor":"Người dùng","flow":["1. Người dùng xem chi tiết thông tin chung của một vật tư, thiết bị. Hệ thống hiển thị chi tiết về thông tin chung của vật tư, thiết bị"],"tags":["Web"],"complexity":"simple","transactions":1,"necessity":"B"},
{"sort":34,"code":"UC-027","parent":"W-III","kind":"usecase","title":"Xem thông tin Hồ sơ vật tư, thiết bị - hợp đồng","actor":"Người dùng","flow":["1. Người dùng xem chi tiết hợp đồng của một vật tư, thiết bị. Hệ thống hiển thị chi tiết về hợp đồng của vật tư, thiết bị"],"tags":["Web"],"complexity":"simple","transactions":1,"necessity":"B"},
{"sort":35,"code":"UC-028","parent":"W-III","kind":"usecase","title":"Xem thông tin Hồ sơ vật tư, thiết bị - thông tin tồn kho","actor":"Người dùng","flow":["1. Người dùng xem chi tiết thông tin tồn kho của một vật tư, thiết bị. Hệ thống hiển thị chi tiết về thông tin kho của vật tư, thiết bị"],"tags":["Web"],"complexity":"simple","transactions":1,"necessity":"B"},
{"sort":36,"code":"UC-029","parent":"W-III","kind":"usecase","title":"Xem thông tin Hồ sơ vật tư, thiết bị - Lịch sử điều chuyển","actor":"Người dùng","flow":["1. Người dùng tìm kiếm lịch sử điều chuyển của vật tư, thiết bị. Hệ thống tìm kiếm và trả kết quả cho người dùng","2. Người dùng xem danh sách lịch sử điều chuyển có phân trang. Hệ thống thực hiện chuyển trang theo yêu cầu","3. Người dùng xem chi tiết lịch sử điều chuyển của một vật tư, thiết bị. Hệ thống hiển thị chi tiết về lịch sử điều chuyển của vật tư, thiết bị"],"tags":["Web"],"complexity":"simple","transactions":3,"necessity":"B"},
{"sort":37,"code":"UC-030","parent":"W-III","kind":"usecase","title":"Xem thông tin vật tư, thiết bị - thông tin Kế toán","actor":"Người dùng","flow":["1. Người dùng xem chi tiết thông tin Kế toáncủa một vật tư, thiết bị. Hệ thống hiển thị chi tiết về Kế toán của vật tư, thiết bị bao gồm: Nguyên giá, khấu hao, giá trị thanh lý"],"tags":["Web"],"complexity":"simple","transactions":1,"necessity":"B"},
{"sort":38,"code":"UC-031","parent":"W-III","kind":"usecase","title":"Xem thông tin Hồ sơ vật tư, thiết bị - thông tin vận hành","actor":"Người dùng","flow":["1. Người dùng tìm kiếm thông tin vận hành của vật tư, thiết bị. Hệ thống tìm kiếm và trả kết quả cho người dùng","2. Người dùng xem chi tiết thông tin vận hành của một vật tư, thiết bị. Hệ thống hiển thị chi tiết về Vận hành của vật tư, thiết bị bao gồm: + Vị trí, + Thông số kỹ thuật, + Thông số vận hành, + Lịch sử lắp đặt, + Lịch sử kiểm tra, thí nghiệm, + Thông tin sửa chữa, + Thông tin sự cố"],"tags":["Web"],"complexity":"simple","transactions":2,"necessity":"B"},
{"sort":39,"code":"W-IV","parent":null,"kind":"group","title":"Cảnh báo","actor":"","flow":[],"tags":["Web"],"complexity":null,"transactions":null,"necessity":"B"},
{"sort":40,"code":"UC-032","parent":"W-IV","kind":"usecase","title":"Cảnh báo mã định danh chưa được dán","actor":"Người dùng","flow":["1. Người dùng xem mã định danh chưa được dán có phân trang. Hệ thống thực hiện chuyển trang theo yêu cầu"],"tags":["Web"],"complexity":"simple","transactions":1,"necessity":"B"},
{"sort":41,"code":"UC-033","parent":"W-IV","kind":"usecase","title":"Cảnh báo kế hoạch định danh chưa hoàn thành","actor":"Người dùng","flow":["1. Người dùng xem kế hoạch định danh chưa hoàn thành có phân trang. Hệ thống thực hiện chuyển trang theo yêu cầu"],"tags":["Web"],"complexity":"simple","transactions":1,"necessity":"B"},
{"sort":42,"code":"UC-034","parent":"W-IV","kind":"usecase","title":"Cảnh báo mã định danh chưa mapping","actor":"Người dùng","flow":["1. Người dùng xem mã định danh chưa mapping có phân trang. Hệ thống thực hiện chuyển trang theo yêu cầu"],"tags":["Web"],"complexity":"simple","transactions":1,"necessity":"B"},
{"sort":43,"code":"UC-035","parent":"W-IV","kind":"usecase","title":"Cảnh báo thiết bị đã nhập trên ERP nhưng quá hạn chưa được định danh","actor":"Người dùng","flow":["1. Người dùng xem thiết bị đã nhập trên ERP nhưng quá hạn chưa được định danh có phân trang. Hệ thống thực hiện chuyển trang theo yêu cầu"],"tags":["Web"],"complexity":"simple","transactions":1,"necessity":"B"},
{"sort":44,"code":"UC-036","parent":"W-IV","kind":"usecase","title":"Cảnh báo vật tư đã xuất kho nhưng chưa được treo tháo","actor":"Người dùng","flow":["1. Người dùng xem vật tư đã xuất kho nhưng chưa được treo tháo có phân trang. Hệ thống thực hiện chuyển trang theo yêu cầu"],"tags":["Web"],"complexity":"simple","transactions":1,"necessity":"B"},
{"sort":45,"code":"UC-037","parent":"W-IV","kind":"usecase","title":"Cảnh báo thiết bị xuống lưới nhưng không nhập kho","actor":"Người dùng","flow":["1. Người dùng xem thiết bị xuống lưới nhưng không nhập kho có phân trang. Hệ thống thực hiện chuyển trang theo yêu cầu"],"tags":["Web"],"complexity":"simple","transactions":1,"necessity":"B"}]
$json$::jsonb)
        as x(sort integer, code text, parent text, kind text, title text, actor text, flow jsonb, tags jsonb,
             complexity text, transactions integer, necessity text)
     order by sort
  loop
    v_parent := null;
    if r.parent is not null then
      select id into v_parent from public.use_cases where project_id = v_project and code = r.parent;
      if v_parent is null then
        raise exception 'Không tìm thấy use case cha % của %', r.parent, r.code;
      end if;
    end if;

    insert into public.use_cases
      (project_id, parent_id, code, title, actor, main_flow, kind, tags, complexity, transactions, necessity)
    values
      (v_project, v_parent, r.code, r.title, coalesce(r.actor, ''),
       array(select jsonb_array_elements_text(r.flow)),
       r.kind, array(select jsonb_array_elements_text(r.tags)), r.complexity, r.transactions, coalesce(r.necessity, 'B'))
    on conflict (project_id, code) do update
      set parent_id = excluded.parent_id,
          title = excluded.title,
          actor = excluded.actor,
          main_flow = excluded.main_flow,
          kind = excluded.kind,
          tags = excluded.tags,
          complexity = excluded.complexity,
          transactions = excluded.transactions,
          necessity = excluded.necessity
    returning (xmax = 0) into v_new;

    if v_new then n_new := n_new + 1; else n_upd := n_upd + 1; end if;
  end loop;

  raise notice 'Nhập xong: % use case/nhóm mới, % cập nhật.', n_new, n_upd;
end
$import$;

-- Kiểm tra nhanh: kỳ vọng 8 nhóm và 37 use case.
select kind, count(*) as so_luong
  from public.use_cases
 where project_id = (select id from public.projects where code = 'GPDN_DNMB_EVNNPC_QTVT_251004')
   and code in ('W-I', 'W-I.1', 'UC-001', 'UC-002', 'UC-003', 'W-I.2', 'UC-004', 'UC-005', 'UC-006', 'UC-007', 'UC-008', 'UC-009', 'UC-010', 'W-I.3', 'UC-011', 'UC-012', 'UC-013', 'UC-014', 'UC-015', 'UC-016', 'W-I.4', 'UC-017', 'UC-018', 'W-II', 'UC-019', 'UC-020', 'UC-021', 'UC-022', 'UC-023', 'W-III', 'UC-024', 'UC-025', 'UC-026', 'UC-027', 'UC-028', 'UC-029', 'UC-030', 'UC-031', 'W-IV', 'UC-032', 'UC-033', 'UC-034', 'UC-035', 'UC-036', 'UC-037')
 group by kind
 order by kind;
