-- Nhập danh sách Use Case dự án GPDN_DNMB_EVNNPC_QTVT_251004 - phần Tích hợp dữ liệu
-- Nguồn: Danh sách chức năng điều chỉnh BCC Vật tư_0508.xlsx (sheet UC sau điều chỉnh final)
-- Gồm 2 module/nhóm (kind = group) và 77 use case (kind = usecase), cây tối đa 3 cấp.
-- Sinh tự động bởi scripts/gen-usecase-import.py - đừng sửa tay, hãy sửa Excel rồi sinh lại.
--
-- Chạy SAU migration 0009_usecase_attributes.sql, trong Supabase SQL Editor.
-- An toàn khi chạy lại: khớp theo (dự án, mã); chỉ cập nhật tên/tác nhân/luồng/nhãn/độ phức tạp/transaction,
-- KHÔNG ghi đè trạng thái, tiến độ, người phụ trách, mô tả hay tiêu chí nghiệm thu đã nhập tay.
-- Hoàn tác: chạy qtvt_usecases_rollback.sql.

do $import$
declare
  v_project_code constant text := 'GPDN_DNMB_EVNNPC_QTVT_251004';
  v_project uuid;
  r record;
  v_parent uuid;
  v_new boolean;
  n_new integer := 0;
  n_upd integer := 0;
begin
  select id into v_project from public.projects where code = v_project_code;
  if v_project is null then
    raise exception 'Không tìm thấy dự án có mã %. Kiểm tra lại mã dự án.', v_project_code;
  end if;

  for r in
    select *
      from jsonb_to_recordset($json$[{"sort":70,"code":"TH","parent":null,"kind":"group","title":"Tích hợp dữ liệu","actor":"","flow":[],"tags":["Tích hợp dữ liệu"],"complexity":null,"transactions":null,"necessity":"B"},
{"sort":71,"code":"TH-I","parent":"TH","kind":"group","title":"Lấy dữ liệu từ Kho","actor":"","flow":[],"tags":["Tích hợp dữ liệu"],"complexity":null,"transactions":null,"necessity":"B"},
{"sort":72,"code":"UC-057","parent":"TH-I","kind":"usecase","title":"Lấy dữ liệu danh mục nhà cung cấp","actor":"Kho dữ liệu","flow":["1. Hệ thống yêu cầu kết nối đến Kho dữ liệu. Kho dữ liệu phản hồi thông tin yêu cầu xác thực.","2. Hệ thống gửi thông tin xác thực. Kho dữ liệu xác thực thông tin và phản hồi lại kết quả kết nối: cho phép kết nối nếu xác thực thành công, từ chối mở kết nối nếu không xác thực thành công","3. Hệ thống Lấy dữ liệu danh mục nhà cung cấp. Kho dữ liệu đẩy dữ liệu danh mục nhà cung cấp","4. Hệ thống gửi yêu cầu đóng kết nối tới Kho dữ liệu và lưu danh mục nhà cung cấp vào CSDL"],"tags":["Tích hợp dữ liệu"],"complexity":"medium","transactions":4,"necessity":"B"},
{"sort":73,"code":"UC-058","parent":"TH-I","kind":"usecase","title":"Lấy dữ liệu danh mục nhà sản xuất","actor":"Kho dữ liệu","flow":["1. Hệ thống yêu cầu kết nối đến Kho dữ liệu. Kho dữ liệu phản hồi thông tin yêu cầu xác thực.","2. Hệ thống gửi thông tin xác thực. Kho dữ liệu xác thực thông tin và phản hồi lại kết quả kết nối: cho phép kết nối nếu xác thực thành công, từ chối mở kết nối nếu không xác thực thành công","3. Hệ thống Lấy dữ liệu danh mục nhà sản xuất. Kho dữ liệu đẩy dữ liệu danh mục nhà sản xuất","4. Hệ thống gửi yêu cầu đóng kết nối tới Kho dữ liệu và lưu danh mục nhà sản xuất vào CSDL"],"tags":["Tích hợp dữ liệu"],"complexity":"medium","transactions":4,"necessity":"B"},
{"sort":74,"code":"UC-059","parent":"TH-I","kind":"usecase","title":"Lấy dữ liệu danh mục VTTB","actor":"Kho dữ liệu","flow":["1. Hệ thống yêu cầu kết nối đến Kho dữ liệu. Kho dữ liệu phản hồi thông tin yêu cầu xác thực.","2. Hệ thống gửi thông tin xác thực. Kho dữ liệu xác thực thông tin và phản hồi lại kết quả kết nối: cho phép kết nối nếu xác thực thành công, từ chối mở kết nối nếu không xác thực thành công","3. Hệ thống Lấy dữ liệu danh mục VTTB. Kho dữ liệu đẩy dữ liệu danh mục VTTB","4. Hệ thống gửi yêu cầu đóng kết nối tới Kho dữ liệu và lưu danh mục VTTB vào CSDL"],"tags":["Tích hợp dữ liệu"],"complexity":"medium","transactions":4,"necessity":"B"},
{"sort":75,"code":"UC-060","parent":"TH-I","kind":"usecase","title":"Lấy dữ liệu danh mục Kho","actor":"Kho dữ liệu","flow":["1. Hệ thống yêu cầu kết nối đến Kho dữ liệu. Kho dữ liệu phản hồi thông tin yêu cầu xác thực.","2. Hệ thống gửi thông tin xác thực. Kho dữ liệu xác thực thông tin và phản hồi lại kết quả kết nối: cho phép kết nối nếu xác thực thành công, từ chối mở kết nối nếu không xác thực thành công","3. Hệ thống Lấy dữ liệu danh mục Kho. Kho dữ liệu đẩy dữ liệu danh mục Kho","4. Hệ thống gửi yêu cầu đóng kết nối tới Kho dữ liệu và lưu danh mục Kho vào CSDL"],"tags":["Tích hợp dữ liệu"],"complexity":"medium","transactions":4,"necessity":"B"},
{"sort":76,"code":"UC-061","parent":"TH-I","kind":"usecase","title":"Lấy danh mục nhân viên","actor":"Kho dữ liệu","flow":["1. Hệ thống yêu cầu kết nối đến Kho dữ liệu. Kho dữ liệu phản hồi thông tin yêu cầu xác thực.","2. Hệ thống gửi thông tin xác thực. Kho dữ liệu xác thực thông tin và phản hồi lại kết quả kết nối: cho phép kết nối nếu xác thực thành công, từ chối mở kết nối nếu không xác thực thành công","3. Hệ thống Lấy danh mục nhân viên. Kho dữ liệu đẩy dữ liệu nhân viên","4. Hệ thống gửi yêu cầu đóng kết nối tới Kho dữ liệu và lưu nhân viên vào CSDL"],"tags":["Tích hợp dữ liệu"],"complexity":"medium","transactions":4,"necessity":"B"},
{"sort":77,"code":"UC-062","parent":"TH-I","kind":"usecase","title":"Lấy dữ liệu Thông tin hợp đồng","actor":"Kho dữ liệu","flow":["1. Hệ thống yêu cầu kết nối đến Kho dữ liệu. Kho dữ liệu phản hồi thông tin yêu cầu xác thực.","2. Hệ thống gửi thông tin xác thực. Kho dữ liệu xác thực thông tin và phản hồi lại kết quả kết nối: cho phép kết nối nếu xác thực thành công, từ chối mở kết nối nếu không xác thực thành công","3. Hệ thống Lấy dữ liệu Thông tin hợp đồng. Kho dữ liệu đẩy dữ liệu Thông tin hợp đồng","4. Hệ thống gửi yêu cầu đóng kết nối tới Kho dữ liệu và lưu Thông tin hợp đồng vào CSDL"],"tags":["Tích hợp dữ liệu"],"complexity":"medium","transactions":4,"necessity":"B"},
{"sort":78,"code":"UC-063","parent":"TH-I","kind":"usecase","title":"Lấy dữ liệu tồn kho","actor":"Kho dữ liệu","flow":["1. Hệ thống yêu cầu kết nối đến Kho dữ liệu. Kho dữ liệu phản hồi thông tin yêu cầu xác thực.","2. Hệ thống gửi thông tin xác thực. Kho dữ liệu xác thực thông tin và phản hồi lại kết quả kết nối: cho phép kết nối nếu xác thực thành công, từ chối mở kết nối nếu không xác thực thành công","3. Hệ thống Lấy dữ liệu tồn kho. Kho dữ liệu đẩy dữ liệu tồn kho","4. Hệ thống gửi yêu cầu đóng kết nối tới Kho dữ liệu và lưu tồn kho vào CSDL"],"tags":["Tích hợp dữ liệu"],"complexity":"medium","transactions":4,"necessity":"B"},
{"sort":79,"code":"UC-064","parent":"TH-I","kind":"usecase","title":"Lấy dữ liệu nhập kho","actor":"Kho dữ liệu","flow":["1. Hệ thống yêu cầu kết nối đến Kho dữ liệu. Kho dữ liệu phản hồi thông tin yêu cầu xác thực.","2. Hệ thống gửi thông tin xác thực. Kho dữ liệu xác thực thông tin và phản hồi lại kết quả kết nối: cho phép kết nối nếu xác thực thành công, từ chối mở kết nối nếu không xác thực thành công","3. Hệ thống Lấy dữ liệu nhập kho. Kho dữ liệu đẩy dữ liệu nhập kho","4. Hệ thống gửi yêu cầu đóng kết nối tới Kho dữ liệu và lưu nhập kho vào CSDL"],"tags":["Tích hợp dữ liệu"],"complexity":"medium","transactions":4,"necessity":"B"},
{"sort":80,"code":"UC-065","parent":"TH-I","kind":"usecase","title":"Lấy dữ liệu xuất kho","actor":"Kho dữ liệu","flow":["1. Hệ thống yêu cầu kết nối đến Kho dữ liệu. Kho dữ liệu phản hồi thông tin yêu cầu xác thực.","2. Hệ thống gửi thông tin xác thực. Kho dữ liệu xác thực thông tin và phản hồi lại kết quả kết nối: cho phép kết nối nếu xác thực thành công, từ chối mở kết nối nếu không xác thực thành công","3. Hệ thống Lấy dữ liệu xuất kho. Kho dữ liệu đẩy dữ liệu xuất kho","4. Hệ thống gửi yêu cầu đóng kết nối tới Kho dữ liệu và lưu xuất kho vào CSDL"],"tags":["Tích hợp dữ liệu"],"complexity":"medium","transactions":4,"necessity":"B"},
{"sort":81,"code":"UC-066","parent":"TH-I","kind":"usecase","title":"Lấy dữ liệu điều chuyển","actor":"Kho dữ liệu","flow":["1. Hệ thống yêu cầu kết nối đến Kho dữ liệu. Kho dữ liệu phản hồi thông tin yêu cầu xác thực.","2. Hệ thống gửi thông tin xác thực. Kho dữ liệu xác thực thông tin và phản hồi lại kết quả kết nối: cho phép kết nối nếu xác thực thành công, từ chối mở kết nối nếu không xác thực thành công","3. Hệ thống Lấy dữ liệu điều chuyển. Kho dữ liệu đẩy dữ liệu điều chuyển","4. Hệ thống gửi yêu cầu đóng kết nối tới Kho dữ liệu và lưu điều chuyển vào CSDL"],"tags":["Tích hợp dữ liệu"],"complexity":"medium","transactions":4,"necessity":"B"},
{"sort":82,"code":"UC-067","parent":"TH-I","kind":"usecase","title":"Lấy dữ liệu thanh lý","actor":"Kho dữ liệu","flow":["1. Hệ thống yêu cầu kết nối đến Kho dữ liệu. Kho dữ liệu phản hồi thông tin yêu cầu xác thực.","2. Hệ thống gửi thông tin xác thực. Kho dữ liệu xác thực thông tin và phản hồi lại kết quả kết nối: cho phép kết nối nếu xác thực thành công, từ chối mở kết nối nếu không xác thực thành công","3. Hệ thống Lấy dữ liệu thanh lý. Kho dữ liệu đẩy dữ liệu thanh lý","4. Hệ thống gửi yêu cầu đóng kết nối tới Kho dữ liệu và lưu thanh lý vào CSDL"],"tags":["Tích hợp dữ liệu"],"complexity":"medium","transactions":4,"necessity":"B"},
{"sort":83,"code":"UC-068","parent":"TH-I","kind":"usecase","title":"Lấy dữ liệu khấu hao","actor":"Kho dữ liệu","flow":["1. Hệ thống yêu cầu kết nối đến Kho dữ liệu. Kho dữ liệu phản hồi thông tin yêu cầu xác thực.","2. Hệ thống gửi thông tin xác thực. Kho dữ liệu xác thực thông tin và phản hồi lại kết quả kết nối: cho phép kết nối nếu xác thực thành công, từ chối mở kết nối nếu không xác thực thành công","3. Hệ thống Lấy dữ liệu khấu hao. Kho dữ liệu đẩy dữ liệu khấu hao","4. Hệ thống gửi yêu cầu đóng kết nối tới Kho dữ liệu và lưu khấu hao vào CSDL"],"tags":["Tích hợp dữ liệu"],"complexity":"medium","transactions":4,"necessity":"B"},
{"sort":84,"code":"UC-069","parent":"TH-I","kind":"usecase","title":"Lấy dữ liệu thiết bị - Hồ sơ công tơ","actor":"Kho dữ liệu","flow":["1. Hệ thống yêu cầu kết nối đến Kho dữ liệu. Kho dữ liệu phản hồi thông tin yêu cầu xác thực.","2. Hệ thống gửi thông tin xác thực. Kho dữ liệu xác thực thông tin và phản hồi lại kết quả kết nối: cho phép kết nối nếu xác thực thành công, từ chối mở kết nối nếu không xác thực thành công","3. Hệ thống Lấy dữ liệu thiết bị - Hồ sơ công tơ. Kho dữ liệu đẩy dữ liệu thiết bị - Hồ sơ công tơ","4. Hệ thống gửi yêu cầu đóng kết nối tới Kho dữ liệu và lưu thiết bị - Hồ sơ công tơ vào CSDL"],"tags":["Tích hợp dữ liệu"],"complexity":"medium","transactions":4,"necessity":"B"},
{"sort":85,"code":"UC-070","parent":"TH-I","kind":"usecase","title":"Lấy dữ liệu thiết bị - Hồ sơ máy biến áp trạm 110kV","actor":"Kho dữ liệu","flow":["1. Hệ thống yêu cầu kết nối đến Kho dữ liệu. Kho dữ liệu phản hồi thông tin yêu cầu xác thực.","2. Hệ thống gửi thông tin xác thực. Kho dữ liệu xác thực thông tin và phản hồi lại kết quả kết nối: cho phép kết nối nếu xác thực thành công, từ chối mở kết nối nếu không xác thực thành công","3. Hệ thống Lấy dữ liệu thiết bị - Hồ sơ máy biến áp trạm 110kV. Kho dữ liệu đẩy dữ liệu thiết bị - Hồ sơ máy biến áp trạm 110kV","4. Hệ thống gửi yêu cầu đóng kết nối tới Kho dữ liệu và lưu thiết bị - Hồ sơ máy biến áp trạm 110kV vào CSDL"],"tags":["Tích hợp dữ liệu"],"complexity":"medium","transactions":4,"necessity":"B"},
{"sort":86,"code":"UC-071","parent":"TH-I","kind":"usecase","title":"Lấy dữ liệu thiết bị - Hồ sơ bộ điều áp dưới tải MBA 110kV","actor":"Kho dữ liệu","flow":["1. Hệ thống yêu cầu kết nối đến Kho dữ liệu. Kho dữ liệu phản hồi thông tin yêu cầu xác thực.","2. Hệ thống gửi thông tin xác thực. Kho dữ liệu xác thực thông tin và phản hồi lại kết quả kết nối: cho phép kết nối nếu xác thực thành công, từ chối mở kết nối nếu không xác thực thành công","3. Hệ thống Lấy dữ liệu thiết bị - Hồ sơ bộ điều áp dưới tải MBA 110kV. Kho dữ liệu đẩy dữ liệu thiết bị - Hồ sơ bộ điều áp dưới tải MBA 110kV","4. Hệ thống gửi yêu cầu đóng kết nối tới Kho dữ liệu và lưu thiết bị - Hồ sơ bộ điều áp dưới tải MBA 110kV vào CSDL"],"tags":["Tích hợp dữ liệu"],"complexity":"medium","transactions":4,"necessity":"B"},
{"sort":87,"code":"UC-072","parent":"TH-I","kind":"usecase","title":"Lấy dữ liệu thiết bị - Hồ sơ máy cắt trạm 110kV","actor":"Kho dữ liệu","flow":["1. Hệ thống yêu cầu kết nối đến Kho dữ liệu. Kho dữ liệu phản hồi thông tin yêu cầu xác thực.","2. Hệ thống gửi thông tin xác thực. Kho dữ liệu xác thực thông tin và phản hồi lại kết quả kết nối: cho phép kết nối nếu xác thực thành công, từ chối mở kết nối nếu không xác thực thành công","3. Hệ thống Lấy dữ liệu thiết bị - Hồ sơ máy cắt trạm 110kV. Kho dữ liệu đẩy dữ liệu thiết bị - Hồ sơ máy cắt trạm 110kV","4. Hệ thống gửi yêu cầu đóng kết nối tới Kho dữ liệu và lưu thiết bị - Hồ sơ máy cắt trạm 110kV vào CSDL"],"tags":["Tích hợp dữ liệu"],"complexity":"medium","transactions":4,"necessity":"B"},
{"sort":88,"code":"UC-073","parent":"TH-I","kind":"usecase","title":"Lấy dữ liệu thiết bị - Hồ sơ dao cách ly trạm 110kV","actor":"Kho dữ liệu","flow":["1. Hệ thống yêu cầu kết nối đến Kho dữ liệu. Kho dữ liệu phản hồi thông tin yêu cầu xác thực.","2. Hệ thống gửi thông tin xác thực. Kho dữ liệu xác thực thông tin và phản hồi lại kết quả kết nối: cho phép kết nối nếu xác thực thành công, từ chối mở kết nối nếu không xác thực thành công","3. Hệ thống Lấy dữ liệu thiết bị - Hồ sơ dao cách ly trạm 110kV. Kho dữ liệu đẩy dữ liệu thiết bị - Hồ sơ dao cách ly trạm 110kV","4. Hệ thống gửi yêu cầu đóng kết nối tới Kho dữ liệu và lưu thiết bị - Hồ sơ dao cách ly trạm 110kV vào CSDL"],"tags":["Tích hợp dữ liệu"],"complexity":"medium","transactions":4,"necessity":"B"},
{"sort":89,"code":"UC-074","parent":"TH-I","kind":"usecase","title":"Lấy dữ liệu thiết bị - Hồ sơ máy biến dòng điện trạm 110kV","actor":"Kho dữ liệu","flow":["1. Hệ thống yêu cầu kết nối đến Kho dữ liệu. Kho dữ liệu phản hồi thông tin yêu cầu xác thực.","2. Hệ thống gửi thông tin xác thực. Kho dữ liệu xác thực thông tin và phản hồi lại kết quả kết nối: cho phép kết nối nếu xác thực thành công, từ chối mở kết nối nếu không xác thực thành công","3. Hệ thống Lấy dữ liệu thiết bị - Hồ sơ máy biến dòng điện trạm 110kV. Kho dữ liệu đẩy dữ liệu thiết bị - Hồ sơ máy biến dòng điện trạm 110kV","4. Hệ thống gửi yêu cầu đóng kết nối tới Kho dữ liệu và lưu thiết bị - Hồ sơ máy biến dòng điện trạm 110kV vào CSDL"],"tags":["Tích hợp dữ liệu"],"complexity":"medium","transactions":4,"necessity":"B"},
{"sort":90,"code":"UC-075","parent":"TH-I","kind":"usecase","title":"Lấy dữ liệu thiết bị - Hồ sơ máy biến điện áp trạm 110kV","actor":"Kho dữ liệu","flow":["1. Hệ thống yêu cầu kết nối đến Kho dữ liệu. Kho dữ liệu phản hồi thông tin yêu cầu xác thực.","2. Hệ thống gửi thông tin xác thực. Kho dữ liệu xác thực thông tin và phản hồi lại kết quả kết nối: cho phép kết nối nếu xác thực thành công, từ chối mở kết nối nếu không xác thực thành công","3. Hệ thống Lấy dữ liệu thiết bị - Hồ sơ máy biến điện áp trạm 110kV. Kho dữ liệu đẩy dữ liệu thiết bị - Hồ sơ máy biến điện áp trạm 110kV","4. Hệ thống gửi yêu cầu đóng kết nối tới Kho dữ liệu và lưu thiết bị - Hồ sơ máy biến điện áp trạm 110kV vào CSDL"],"tags":["Tích hợp dữ liệu"],"complexity":"medium","transactions":4,"necessity":"B"},
{"sort":91,"code":"UC-076","parent":"TH-I","kind":"usecase","title":"Lấy dữ liệu thiết bị - Hồ sơ chống sét van trạm 110kV","actor":"Kho dữ liệu","flow":["1. Hệ thống yêu cầu kết nối đến Kho dữ liệu. Kho dữ liệu phản hồi thông tin yêu cầu xác thực.","2. Hệ thống gửi thông tin xác thực. Kho dữ liệu xác thực thông tin và phản hồi lại kết quả kết nối: cho phép kết nối nếu xác thực thành công, từ chối mở kết nối nếu không xác thực thành công","3. Hệ thống Lấy dữ liệu thiết bị - Hồ sơ chống sét van trạm 110kV. Kho dữ liệu đẩy dữ liệu thiết bị - Hồ sơ chống sét van trạm 110kV","4. Hệ thống gửi yêu cầu đóng kết nối tới Kho dữ liệu và lưu thiết bị - Hồ sơ chống sét van trạm 110kV vào CSDL"],"tags":["Tích hợp dữ liệu"],"complexity":"medium","transactions":4,"necessity":"B"},
{"sort":92,"code":"UC-077","parent":"TH-I","kind":"usecase","title":"Lấy dữ liệu thiết bị - Hồ sơ tụ bù trạm 110kV","actor":"Kho dữ liệu","flow":["1. Hệ thống yêu cầu kết nối đến Kho dữ liệu. Kho dữ liệu phản hồi thông tin yêu cầu xác thực.","2. Hệ thống gửi thông tin xác thực. Kho dữ liệu xác thực thông tin và phản hồi lại kết quả kết nối: cho phép kết nối nếu xác thực thành công, từ chối mở kết nối nếu không xác thực thành công","3. Hệ thống Lấy dữ liệu thiết bị - Hồ sơ tụ bù trạm 110kV. Kho dữ liệu đẩy dữ liệu thiết bị - Hồ sơ tụ bù trạm 110kV","4. Hệ thống gửi yêu cầu đóng kết nối tới Kho dữ liệu và lưu thiết bị - Hồ sơ tụ bù trạm 110kV vào CSDL"],"tags":["Tích hợp dữ liệu"],"complexity":"medium","transactions":4,"necessity":"B"},
{"sort":93,"code":"UC-078","parent":"TH-I","kind":"usecase","title":"Lấy dữ liệu thiết bị - Hồ sơ kháng điện trạm 110kV","actor":"Kho dữ liệu","flow":["1. Hệ thống yêu cầu kết nối đến Kho dữ liệu. Kho dữ liệu phản hồi thông tin yêu cầu xác thực.","2. Hệ thống gửi thông tin xác thực. Kho dữ liệu xác thực thông tin và phản hồi lại kết quả kết nối: cho phép kết nối nếu xác thực thành công, từ chối mở kết nối nếu không xác thực thành công","3. Hệ thống Lấy dữ liệu thiết bị - Hồ sơ kháng điện trạm 110kV. Kho dữ liệu đẩy dữ liệu thiết bị - Hồ sơ kháng điện trạm 110kV","4. Hệ thống gửi yêu cầu đóng kết nối tới Kho dữ liệu và lưu thiết bị - Hồ sơ kháng điện trạm 110kV vào CSDL"],"tags":["Tích hợp dữ liệu"],"complexity":"medium","transactions":4,"necessity":"B"},
{"sort":94,"code":"UC-079","parent":"TH-I","kind":"usecase","title":"Lấy dữ liệu thiết bị - Hồ sơ ắc quy điện trạm 110kV","actor":"Kho dữ liệu","flow":["1. Hệ thống yêu cầu kết nối đến Kho dữ liệu. Kho dữ liệu phản hồi thông tin yêu cầu xác thực.","2. Hệ thống gửi thông tin xác thực. Kho dữ liệu xác thực thông tin và phản hồi lại kết quả kết nối: cho phép kết nối nếu xác thực thành công, từ chối mở kết nối nếu không xác thực thành công","3. Hệ thống Lấy dữ liệu thiết bị - Hồ sơ ắc quy điện trạm 110kV. Kho dữ liệu đẩy dữ liệu thiết bị - Hồ sơ ắc quy điện trạm 110kV","4. Hệ thống gửi yêu cầu đóng kết nối tới Kho dữ liệu và lưu thiết bị - Hồ sơ ắc quy điện trạm 110kV vào CSDL"],"tags":["Tích hợp dữ liệu"],"complexity":"medium","transactions":4,"necessity":"B"},
{"sort":95,"code":"UC-080","parent":"TH-I","kind":"usecase","title":"Lấy dữ liệu thiết bị - Hồ sơ MBA tự dùng trạm 110kV","actor":"Kho dữ liệu","flow":["1. Hệ thống yêu cầu kết nối đến Kho dữ liệu. Kho dữ liệu phản hồi thông tin yêu cầu xác thực.","2. Hệ thống gửi thông tin xác thực. Kho dữ liệu xác thực thông tin và phản hồi lại kết quả kết nối: cho phép kết nối nếu xác thực thành công, từ chối mở kết nối nếu không xác thực thành công","3. Hệ thống Lấy dữ liệu thiết bị - Hồ sơ MBA tự dùng trạm 110kV. Kho dữ liệu đẩy dữ liệu thiết bị - Hồ sơ MBA tự dùng trạm 110kV","4. Hệ thống gửi yêu cầu đóng kết nối tới Kho dữ liệu và lưu thiết bị - Hồ sơ MBA tự dùng trạm 110kV vào CSDL"],"tags":["Tích hợp dữ liệu"],"complexity":"medium","transactions":4,"necessity":"B"},
{"sort":96,"code":"UC-081","parent":"TH-I","kind":"usecase","title":"Lấy dữ liệu thiết bị - Hồ sơ máy cắt trung thế ngoài trời trong TBA 110kV","actor":"Kho dữ liệu","flow":["1. Hệ thống yêu cầu kết nối đến Kho dữ liệu. Kho dữ liệu phản hồi thông tin yêu cầu xác thực.","2. Hệ thống gửi thông tin xác thực. Kho dữ liệu xác thực thông tin và phản hồi lại kết quả kết nối: cho phép kết nối nếu xác thực thành công, từ chối mở kết nối nếu không xác thực thành công","3. Hệ thống Lấy dữ liệu thiết bị - Hồ sơ máy cắt trung thế ngoài trời trong TBA 110kV. Kho dữ liệu đẩy dữ liệu thiết bị - Hồ sơ máy cắt trung thế ngoài trời trong TBA 110kV","4. Hệ thống gửi yêu cầu đóng kết nối tới Kho dữ liệu và lưu thiết bị - Hồ sơ máy cắt trung thế ngoài trời trong TBA 110kV vào CSDL"],"tags":["Tích hợp dữ liệu"],"complexity":"medium","transactions":4,"necessity":"B"},
{"sort":97,"code":"UC-082","parent":"TH-I","kind":"usecase","title":"Lấy dữ liệu thiết bị - Hồ sơ dao cách ly trung thế ngoài trời trong TBA 110kV","actor":"Kho dữ liệu","flow":["1. Hệ thống yêu cầu kết nối đến Kho dữ liệu. Kho dữ liệu phản hồi thông tin yêu cầu xác thực.","2. Hệ thống gửi thông tin xác thực. Kho dữ liệu xác thực thông tin và phản hồi lại kết quả kết nối: cho phép kết nối nếu xác thực thành công, từ chối mở kết nối nếu không xác thực thành công","3. Hệ thống Lấy dữ liệu thiết bị - Hồ sơ dao cách ly trung thế ngoài trời trong TBA 110kV . Kho dữ liệu đẩy dữ liệu thiết bị - Hồ sơ dao cách ly trung thế ngoài trời trong TBA 110kV","4. Hệ thống gửi yêu cầu đóng kết nối tới Kho dữ liệu và lưu thiết bị - Hồ sơ dao cách ly trung thế ngoài trời trong TBA 110kV vào CSDL"],"tags":["Tích hợp dữ liệu"],"complexity":"medium","transactions":4,"necessity":"B"},
{"sort":98,"code":"UC-083","parent":"TH-I","kind":"usecase","title":"Lấy dữ liệu thiết bị - Hồ sơ chống sét van ĐZ 110kV","actor":"Kho dữ liệu","flow":["1. Hệ thống yêu cầu kết nối đến Kho dữ liệu. Kho dữ liệu phản hồi thông tin yêu cầu xác thực.","2. Hệ thống gửi thông tin xác thực. Kho dữ liệu xác thực thông tin và phản hồi lại kết quả kết nối: cho phép kết nối nếu xác thực thành công, từ chối mở kết nối nếu không xác thực thành công","3. Hệ thống Lấy dữ liệu thiết bị - Hồ sơ chống sét van ĐZ 110kV. Kho dữ liệu đẩy dữ liệu thiết bị - Hồ sơ chống sét van ĐZ 110kV","4. Hệ thống gửi yêu cầu đóng kết nối tới Kho dữ liệu và lưu thiết bị - Hồ sơ chống sét van ĐZ 110kV vào CSDL"],"tags":["Tích hợp dữ liệu"],"complexity":"medium","transactions":4,"necessity":"B"},
{"sort":99,"code":"UC-084","parent":"TH-I","kind":"usecase","title":"Lấy dữ liệu thiết bị - Hồ sơ máy biến áp trạm phân phối","actor":"Kho dữ liệu","flow":["1. Hệ thống yêu cầu kết nối đến Kho dữ liệu. Kho dữ liệu phản hồi thông tin yêu cầu xác thực.","2. Hệ thống gửi thông tin xác thực. Kho dữ liệu xác thực thông tin và phản hồi lại kết quả kết nối: cho phép kết nối nếu xác thực thành công, từ chối mở kết nối nếu không xác thực thành công","3. Hệ thống Lấy dữ liệu thiết bị - Hồ sơ máy biến áp trạm phân phối. Kho dữ liệu đẩy dữ liệu thiết bị - Hồ sơ máy biến áp trạm phân phối","4. Hệ thống gửi yêu cầu đóng kết nối tới Kho dữ liệu và lưu thiết bị - Hồ sơ máy biến áp trạm phân phối vào CSDL"],"tags":["Tích hợp dữ liệu"],"complexity":"medium","transactions":4,"necessity":"B"},
{"sort":100,"code":"UC-085","parent":"TH-I","kind":"usecase","title":"Lấy dữ liệu thiết bị - Hồ sơ cầu chì tự rơi trạm phân phối","actor":"Kho dữ liệu","flow":["1. Hệ thống yêu cầu kết nối đến Kho dữ liệu. Kho dữ liệu phản hồi thông tin yêu cầu xác thực.","2. Hệ thống gửi thông tin xác thực. Kho dữ liệu xác thực thông tin và phản hồi lại kết quả kết nối: cho phép kết nối nếu xác thực thành công, từ chối mở kết nối nếu không xác thực thành công","3. Hệ thống Lấy dữ liệu thiết bị - Hồ sơ cầu chì tự rơi trạm phân phối. Kho dữ liệu đẩy dữ liệu thiết bị - Hồ sơ cầu chì tự rơi trạm phân phối","4. Hệ thống gửi yêu cầu đóng kết nối tới Kho dữ liệu và lưu thiết bị - Hồ sơ cầu chì tự rơi trạm phân phối vào CSDL"],"tags":["Tích hợp dữ liệu"],"complexity":"medium","transactions":4,"necessity":"B"},
{"sort":101,"code":"UC-086","parent":"TH-I","kind":"usecase","title":"Lấy dữ liệu thiết bị - Hồ sơ chống sét van trạm phân phối","actor":"Kho dữ liệu","flow":["1. Hệ thống yêu cầu kết nối đến Kho dữ liệu. Kho dữ liệu phản hồi thông tin yêu cầu xác thực.","2. Hệ thống gửi thông tin xác thực. Kho dữ liệu xác thực thông tin và phản hồi lại kết quả kết nối: cho phép kết nối nếu xác thực thành công, từ chối mở kết nối nếu không xác thực thành công","3. Hệ thống Lấy dữ liệu thiết bị - Hồ sơ chống sét van trạm phân phối. Kho dữ liệu đẩy dữ liệu thiết bị - Hồ sơ chống sét van trạm phân phối","4. Hệ thống gửi yêu cầu đóng kết nối tới Kho dữ liệu và lưu thiết bị - Hồ sơ chống sét van trạm phân phối vào CSDL"],"tags":["Tích hợp dữ liệu"],"complexity":"medium","transactions":4,"necessity":"B"},
{"sort":102,"code":"UC-087","parent":"TH-I","kind":"usecase","title":"Lấy dữ liệu thiết bị - Hồ sơ dao cách ly trạm phân phối","actor":"Kho dữ liệu","flow":["1. Hệ thống yêu cầu kết nối đến Kho dữ liệu. Kho dữ liệu phản hồi thông tin yêu cầu xác thực.","2. Hệ thống gửi thông tin xác thực. Kho dữ liệu xác thực thông tin và phản hồi lại kết quả kết nối: cho phép kết nối nếu xác thực thành công, từ chối mở kết nối nếu không xác thực thành công","3. Hệ thống Lấy dữ liệu thiết bị - Hồ sơ dao cách ly trạm phân phối. Kho dữ liệu đẩy dữ liệu thiết bị - Hồ sơ dao cách ly trạm phân phối","4. Hệ thống gửi yêu cầu đóng kết nối tới Kho dữ liệu và lưu thiết bị - Hồ sơ dao cách ly trạm phân phối vào CSDL"],"tags":["Tích hợp dữ liệu"],"complexity":"medium","transactions":4,"necessity":"B"},
{"sort":103,"code":"UC-088","parent":"TH-I","kind":"usecase","title":"Lấy dữ liệu thiết bị - Hồ sơ Attomat hạ thế trạm phân phối","actor":"Kho dữ liệu","flow":["1. Hệ thống yêu cầu kết nối đến Kho dữ liệu. Kho dữ liệu phản hồi thông tin yêu cầu xác thực.","2. Hệ thống gửi thông tin xác thực. Kho dữ liệu xác thực thông tin và phản hồi lại kết quả kết nối: cho phép kết nối nếu xác thực thành công, từ chối mở kết nối nếu không xác thực thành công","3. Hệ thống Lấy dữ liệu thiết bị - Hồ sơ Attomat hạ thế trạm phân phối. Kho dữ liệu đẩy dữ liệu thiết bị - Hồ sơ Attomat hạ thế trạm phân phối","4. Hệ thống gửi yêu cầu đóng kết nối tới Kho dữ liệu và lưu thiết bị - Hồ sơ Attomat hạ thế trạm phân phối vào CSDL"],"tags":["Tích hợp dữ liệu"],"complexity":"medium","transactions":4,"necessity":"B"},
{"sort":104,"code":"UC-089","parent":"TH-I","kind":"usecase","title":"Lấy dữ liệu thiết bị - Hồ sơ tụ bù trạm phân phối","actor":"Kho dữ liệu","flow":["1. Hệ thống yêu cầu kết nối đến Kho dữ liệu. Kho dữ liệu phản hồi thông tin yêu cầu xác thực.","2. Hệ thống gửi thông tin xác thực. Kho dữ liệu xác thực thông tin và phản hồi lại kết quả kết nối: cho phép kết nối nếu xác thực thành công, từ chối mở kết nối nếu không xác thực thành công","3. Hệ thống Lấy dữ liệu thiết bị - Hồ sơ tụ bù trạm phân phối. Kho dữ liệu đẩy dữ liệu thiết bị - Hồ sơ tụ bù trạm phân phối","4. Hệ thống gửi yêu cầu đóng kết nối tới Kho dữ liệu và lưu thiết bị - Hồ sơ tụ bù trạm phân phối vào CSDL"],"tags":["Tích hợp dữ liệu"],"complexity":"medium","transactions":4,"necessity":"B"},
{"sort":105,"code":"UC-090","parent":"TH-I","kind":"usecase","title":"Lấy dữ liệu thiết bị - Hồ sơ máy biến dòng điện trạm phân phối","actor":"Kho dữ liệu","flow":["1. Hệ thống yêu cầu kết nối đến Kho dữ liệu. Kho dữ liệu phản hồi thông tin yêu cầu xác thực.","2. Hệ thống gửi thông tin xác thực. Kho dữ liệu xác thực thông tin và phản hồi lại kết quả kết nối: cho phép kết nối nếu xác thực thành công, từ chối mở kết nối nếu không xác thực thành công","3. Hệ thống Lấy dữ liệu thiết bị - Hồ sơ máy biến dòng điện trạm phân phối. Kho dữ liệu đẩy dữ liệu thiết bị - Hồ sơ máy biến dòng điện trạm phân phối","4. Hệ thống gửi yêu cầu đóng kết nối tới Kho dữ liệu và lưu thiết bị - Hồ sơ máy biến dòng điện trạm phân phối vào CSDL"],"tags":["Tích hợp dữ liệu"],"complexity":"medium","transactions":4,"necessity":"B"},
{"sort":106,"code":"UC-091","parent":"TH-I","kind":"usecase","title":"Lấy dữ liệu thiết bị - Hồ sơ máy biến điện áp trạm phân phối","actor":"Kho dữ liệu","flow":["1. Hệ thống yêu cầu kết nối đến Kho dữ liệu. Kho dữ liệu phản hồi thông tin yêu cầu xác thực.","2. Hệ thống gửi thông tin xác thực. Kho dữ liệu xác thực thông tin và phản hồi lại kết quả kết nối: cho phép kết nối nếu xác thực thành công, từ chối mở kết nối nếu không xác thực thành công","3. Hệ thống Lấy dữ liệu thiết bị - Hồ sơ máy biến điện áp trạm phân phối. Kho dữ liệu đẩy dữ liệu thiết bị - Hồ sơ máy biến điện áp trạm phân phối","4. Hệ thống gửi yêu cầu đóng kết nối tới Kho dữ liệu và lưu thiết bị - Hồ sơ máy biến điện áp trạm phân phối vào CSDL"],"tags":["Tích hợp dữ liệu"],"complexity":"medium","transactions":4,"necessity":"B"},
{"sort":107,"code":"UC-092","parent":"TH-I","kind":"usecase","title":"Lấy dữ liệu thiết bị - Hồ sơ máy cắt Recloser ĐZ TA","actor":"Kho dữ liệu","flow":["1. Hệ thống yêu cầu kết nối đến Kho dữ liệu. Kho dữ liệu phản hồi thông tin yêu cầu xác thực.","2. Hệ thống gửi thông tin xác thực. Kho dữ liệu xác thực thông tin và phản hồi lại kết quả kết nối: cho phép kết nối nếu xác thực thành công, từ chối mở kết nối nếu không xác thực thành công","3. Hệ thống Lấy dữ liệu thiết bị - Hồ sơ máy cắt Recloser ĐZ TA. Kho dữ liệu đẩy dữ liệu thiết bị - Hồ sơ máy cắt Recloser ĐZ TA","4. Hệ thống gửi yêu cầu đóng kết nối tới Kho dữ liệu và lưu thiết bị - Hồ sơ máy cắt Recloser ĐZ TA vào CSDL"],"tags":["Tích hợp dữ liệu"],"complexity":"medium","transactions":4,"necessity":"B"},
{"sort":108,"code":"UC-093","parent":"TH-I","kind":"usecase","title":"Lấy dữ liệu thiết bị - Hồ sơ cầu dao cáo điều khiển ĐZ TA","actor":"Kho dữ liệu","flow":["1. Hệ thống yêu cầu kết nối đến Kho dữ liệu. Kho dữ liệu phản hồi thông tin yêu cầu xác thực.","2. Hệ thống gửi thông tin xác thực. Kho dữ liệu xác thực thông tin và phản hồi lại kết quả kết nối: cho phép kết nối nếu xác thực thành công, từ chối mở kết nối nếu không xác thực thành công","3. Hệ thống Lấy dữ liệu thiết bị - Hồ sơ cầu dao cáo điều khiển ĐZ TA. Kho dữ liệu đẩy dữ liệu thiết bị - Hồ sơ cầu dao cáo điều khiển ĐZ TA","4. Hệ thống gửi yêu cầu đóng kết nối tới Kho dữ liệu và lưu thiết bị - Hồ sơ cầu dao cáo điều khiển ĐZ TA vào CSDL"],"tags":["Tích hợp dữ liệu"],"complexity":"medium","transactions":4,"necessity":"B"},
{"sort":109,"code":"UC-094","parent":"TH-I","kind":"usecase","title":"Lấy dữ liệu thiết bị - Hồ sơ dao cách ly ĐZ TA","actor":"Kho dữ liệu","flow":["1. Hệ thống yêu cầu kết nối đến Kho dữ liệu. Kho dữ liệu phản hồi thông tin yêu cầu xác thực.","2. Hệ thống gửi thông tin xác thực. Kho dữ liệu xác thực thông tin và phản hồi lại kết quả kết nối: cho phép kết nối nếu xác thực thành công, từ chối mở kết nối nếu không xác thực thành công","3. Hệ thống Lấy dữ liệu thiết bị - Hồ sơ dao cách ly ĐZ TA. Kho dữ liệu đẩy dữ liệu thiết bị - Hồ sơ dao cách ly ĐZ TA","4. Hệ thống gửi yêu cầu đóng kết nối tới Kho dữ liệu và lưu thiết bị - Hồ sơ dao cách ly ĐZ TA vào CSDL"],"tags":["Tích hợp dữ liệu"],"complexity":"medium","transactions":4,"necessity":"B"},
{"sort":110,"code":"UC-095","parent":"TH-I","kind":"usecase","title":"Lấy dữ liệu thiết bị - Hồ sơ cầu chì tự rơi ĐZ TA","actor":"Kho dữ liệu","flow":["1. Hệ thống yêu cầu kết nối đến Kho dữ liệu. Kho dữ liệu phản hồi thông tin yêu cầu xác thực.","2. Hệ thống gửi thông tin xác thực. Kho dữ liệu xác thực thông tin và phản hồi lại kết quả kết nối: cho phép kết nối nếu xác thực thành công, từ chối mở kết nối nếu không xác thực thành công","3. Hệ thống Lấy dữ liệu thiết bị - Hồ sơ cầu chì tự rơi ĐZ TA. Kho dữ liệu đẩy dữ liệu thiết bị - Hồ sơ cầu chì tự rơi ĐZ TA","4. Hệ thống gửi yêu cầu đóng kết nối tới Kho dữ liệu và lưu thiết bị - Hồ sơ cầu chì tự rơi ĐZ TA vào CSDL"],"tags":["Tích hợp dữ liệu"],"complexity":"medium","transactions":4,"necessity":"B"},
{"sort":111,"code":"UC-096","parent":"TH-I","kind":"usecase","title":"Lấy dữ liệu thiết bị - Hồ sơ tủ RMU ĐZ TA","actor":"Kho dữ liệu","flow":["1. Hệ thống yêu cầu kết nối đến Kho dữ liệu. Kho dữ liệu phản hồi thông tin yêu cầu xác thực.","2. Hệ thống gửi thông tin xác thực. Kho dữ liệu xác thực thông tin và phản hồi lại kết quả kết nối: cho phép kết nối nếu xác thực thành công, từ chối mở kết nối nếu không xác thực thành công","3. Hệ thống Lấy dữ liệu thiết bị - Hồ sơ tủ RMU ĐZ TA. Kho dữ liệu đẩy dữ liệu thiết bị - Hồ sơ tủ RMU ĐZ TA","4. Hệ thống gửi yêu cầu đóng kết nối tới Kho dữ liệu và lưu thiết bị - Hồ sơ tủ RMU ĐZ TA vào CSDL"],"tags":["Tích hợp dữ liệu"],"complexity":"medium","transactions":4,"necessity":"B"},
{"sort":112,"code":"UC-097","parent":"TH-I","kind":"usecase","title":"Lấy dữ liệu thiết bị - Hồ sơ chống sét van ĐZ TA","actor":"Kho dữ liệu","flow":["1. Hệ thống yêu cầu kết nối đến Kho dữ liệu. Kho dữ liệu phản hồi thông tin yêu cầu xác thực.","2. Hệ thống gửi thông tin xác thực. Kho dữ liệu xác thực thông tin và phản hồi lại kết quả kết nối: cho phép kết nối nếu xác thực thành công, từ chối mở kết nối nếu không xác thực thành công","3. Hệ thống Lấy dữ liệu thiết bị - Hồ sơ chống sét van ĐZ TA. Kho dữ liệu đẩy dữ liệu thiết bị - Hồ sơ chống sét van ĐZ TA","4. Hệ thống gửi yêu cầu đóng kết nối tới Kho dữ liệu và lưu thiết bị - Hồ sơ chống sét van ĐZ TA vào CSDL"],"tags":["Tích hợp dữ liệu"],"complexity":"medium","transactions":4,"necessity":"B"},
{"sort":113,"code":"UC-098","parent":"TH-I","kind":"usecase","title":"Lấy dữ liệu thiết bị - Thông số vận hành công tơ","actor":"Kho dữ liệu","flow":["1. Hệ thống yêu cầu kết nối đến Kho dữ liệu. Kho dữ liệu phản hồi thông tin yêu cầu xác thực.","2. Hệ thống gửi thông tin xác thực. Kho dữ liệu xác thực thông tin và phản hồi lại kết quả kết nối: cho phép kết nối nếu xác thực thành công, từ chối mở kết nối nếu không xác thực thành công","3. Hệ thống Lấy dữ liệu thiết bị - Thông số vận hành công tơ. Kho dữ liệu đẩy dữ liệu thiết bị - Thông số vận hành công tơ","4. Hệ thống gửi yêu cầu đóng kết nối tới Kho dữ liệu và lưu thiết bị - Thông số vận hành công tơ vào CSDL"],"tags":["Tích hợp dữ liệu"],"complexity":"medium","transactions":4,"necessity":"B"},
{"sort":114,"code":"UC-099","parent":"TH-I","kind":"usecase","title":"Lấy dữ liệu thiết bị - Thông số vận hành Máy biến áp trạm 110kV","actor":"Kho dữ liệu","flow":["1. Hệ thống yêu cầu kết nối đến Kho dữ liệu. Kho dữ liệu phản hồi thông tin yêu cầu xác thực.","2. Hệ thống gửi thông tin xác thực. Kho dữ liệu xác thực thông tin và phản hồi lại kết quả kết nối: cho phép kết nối nếu xác thực thành công, từ chối mở kết nối nếu không xác thực thành công","3. Hệ thống Lấy dữ liệu thiết bị - Thông số vận hành Máy biến áp trạm 110kV. Kho dữ liệu đẩy dữ liệu thiết bị - Thông số vận hành Máy biến áp trạm 110kV","4. Hệ thống gửi yêu cầu đóng kết nối tới Kho dữ liệu và lưu thiết bị - Thông số vận hành Máy biến áp trạm 110kV vào CSDL"],"tags":["Tích hợp dữ liệu"],"complexity":"medium","transactions":4,"necessity":"B"},
{"sort":115,"code":"UC-100","parent":"TH-I","kind":"usecase","title":"Lấy dữ liệu thiết bị - Thông số vận hành Bộ điều áp dưới tải MBA 110kV","actor":"Kho dữ liệu","flow":["1. Hệ thống yêu cầu kết nối đến Kho dữ liệu. Kho dữ liệu phản hồi thông tin yêu cầu xác thực.","2. Hệ thống gửi thông tin xác thực. Kho dữ liệu xác thực thông tin và phản hồi lại kết quả kết nối: cho phép kết nối nếu xác thực thành công, từ chối mở kết nối nếu không xác thực thành công","3. Hệ thống Lấy dữ liệu thiết bị - Thông số vận hành Bộ điều áp dưới tải MBA 110kV. Kho dữ liệu đẩy dữ liệu thiết bị - Thông số vận hành Bộ điều áp dưới tải MBA 110kV","4. Hệ thống gửi yêu cầu đóng kết nối tới Kho dữ liệu và lưu thiết bị - Thông số vận hành Bộ điều áp dưới tải MBA 110kV vào CSDL"],"tags":["Tích hợp dữ liệu"],"complexity":"medium","transactions":4,"necessity":"B"},
{"sort":116,"code":"UC-101","parent":"TH-I","kind":"usecase","title":"Lấy dữ liệu thiết bị - Thông số vận hành Máy cắt trạm 110kV","actor":"Kho dữ liệu","flow":["1. Hệ thống yêu cầu kết nối đến Kho dữ liệu. Kho dữ liệu phản hồi thông tin yêu cầu xác thực.","2. Hệ thống gửi thông tin xác thực. Kho dữ liệu xác thực thông tin và phản hồi lại kết quả kết nối: cho phép kết nối nếu xác thực thành công, từ chối mở kết nối nếu không xác thực thành công","3. Hệ thống Lấy dữ liệu thiết bị - Thông số vận hành Máy cắt trạm 110kV. Kho dữ liệu đẩy dữ liệu thiết bị - Thông số vận hành Máy cắt trạm 110kV","4. Hệ thống gửi yêu cầu đóng kết nối tới Kho dữ liệu và lưu thiết bị - Thông số vận hành Máy cắt trạm 110kV vào CSDL"],"tags":["Tích hợp dữ liệu"],"complexity":"medium","transactions":4,"necessity":"B"},
{"sort":117,"code":"UC-102","parent":"TH-I","kind":"usecase","title":"Lấy dữ liệu thiết bị - Thông số vận hành Dao cách ly trạm 110kV","actor":"Kho dữ liệu","flow":["1. Hệ thống yêu cầu kết nối đến Kho dữ liệu. Kho dữ liệu phản hồi thông tin yêu cầu xác thực.","2. Hệ thống gửi thông tin xác thực. Kho dữ liệu xác thực thông tin và phản hồi lại kết quả kết nối: cho phép kết nối nếu xác thực thành công, từ chối mở kết nối nếu không xác thực thành công","3. Hệ thống Lấy dữ liệu thiết bị - Thông số vận hành Dao cách ly trạm 110kV. Kho dữ liệu đẩy dữ liệu thiết bị - Thông số vận hành Dao cách ly trạm 110kV","4. Hệ thống gửi yêu cầu đóng kết nối tới Kho dữ liệu và lưu thiết bị - Thông số vận hành Dao cách ly trạm 110kV vào CSDL"],"tags":["Tích hợp dữ liệu"],"complexity":"medium","transactions":4,"necessity":"B"},
{"sort":118,"code":"UC-103","parent":"TH-I","kind":"usecase","title":"Lấy dữ liệu thiết bị - Thông số vận hành Máy biến dòng điện trạm 110kV","actor":"Kho dữ liệu","flow":["1. Hệ thống yêu cầu kết nối đến Kho dữ liệu. Kho dữ liệu phản hồi thông tin yêu cầu xác thực.","2. Hệ thống gửi thông tin xác thực. Kho dữ liệu xác thực thông tin và phản hồi lại kết quả kết nối: cho phép kết nối nếu xác thực thành công, từ chối mở kết nối nếu không xác thực thành công","3. Hệ thống Lấy dữ liệu thiết bị - Thông số vận hành Máy biến dòng điện trạm 110kV. Kho dữ liệu đẩy dữ liệu thiết bị - Thông số vận hành Máy biến dòng điện trạm 110kV","4. Hệ thống gửi yêu cầu đóng kết nối tới Kho dữ liệu và lưu thiết bị - Thông số vận hành Máy biến dòng điện trạm 110kV vào CSDL"],"tags":["Tích hợp dữ liệu"],"complexity":"medium","transactions":4,"necessity":"B"},
{"sort":119,"code":"UC-104","parent":"TH-I","kind":"usecase","title":"Lấy dữ liệu thiết bị - Thông số vận hành Máy biến điện áp trạm 110kV","actor":"Kho dữ liệu","flow":["1. Hệ thống yêu cầu kết nối đến Kho dữ liệu. Kho dữ liệu phản hồi thông tin yêu cầu xác thực.","2. Hệ thống gửi thông tin xác thực. Kho dữ liệu xác thực thông tin và phản hồi lại kết quả kết nối: cho phép kết nối nếu xác thực thành công, từ chối mở kết nối nếu không xác thực thành công","3. Hệ thống Lấy dữ liệu thiết bị - Thông số vận hành Máy biến điện áp trạm 110kV. Kho dữ liệu đẩy dữ liệu thiết bị - Thông số vận hành Máy biến điện áp trạm 110kV","4. Hệ thống gửi yêu cầu đóng kết nối tới Kho dữ liệu và lưu thiết bị - Thông số vận hành Máy biến điện áp trạm 110kV vào CSDL"],"tags":["Tích hợp dữ liệu"],"complexity":"medium","transactions":4,"necessity":"B"},
{"sort":120,"code":"UC-105","parent":"TH-I","kind":"usecase","title":"Lấy dữ liệu thiết bị - Thông số vận hành Chống sét van trạm 110kV","actor":"Kho dữ liệu","flow":["1. Hệ thống yêu cầu kết nối đến Kho dữ liệu. Kho dữ liệu phản hồi thông tin yêu cầu xác thực.","2. Hệ thống gửi thông tin xác thực. Kho dữ liệu xác thực thông tin và phản hồi lại kết quả kết nối: cho phép kết nối nếu xác thực thành công, từ chối mở kết nối nếu không xác thực thành công","3. Hệ thống Lấy dữ liệu thiết bị - Thông số vận hành Chống sét van trạm 110kV. Kho dữ liệu đẩy dữ liệu thiết bị - Thông số vận hành Chống sét van trạm 110kV","4. Hệ thống gửi yêu cầu đóng kết nối tới Kho dữ liệu và lưu thiết bị - Thông số vận hành Chống sét van trạm 110kV vào CSDL"],"tags":["Tích hợp dữ liệu"],"complexity":"medium","transactions":4,"necessity":"B"},
{"sort":121,"code":"UC-106","parent":"TH-I","kind":"usecase","title":"Lấy dữ liệu thiết bị - Thông số vận hành Tụ bù trạm 110kV","actor":"Kho dữ liệu","flow":["1. Hệ thống yêu cầu kết nối đến Kho dữ liệu. Kho dữ liệu phản hồi thông tin yêu cầu xác thực.","2. Hệ thống gửi thông tin xác thực. Kho dữ liệu xác thực thông tin và phản hồi lại kết quả kết nối: cho phép kết nối nếu xác thực thành công, từ chối mở kết nối nếu không xác thực thành công","3. Hệ thống Lấy dữ liệu thiết bị - Thông số vận hành Tụ bù trạm 110kV. Kho dữ liệu đẩy dữ liệu thiết bị - Thông số vận hành Tụ bù trạm 110kV","4. Hệ thống gửi yêu cầu đóng kết nối tới Kho dữ liệu và lưu thiết bị - Thông số vận hành Tụ bù trạm 110kV vào CSDL"],"tags":["Tích hợp dữ liệu"],"complexity":"medium","transactions":4,"necessity":"B"},
{"sort":122,"code":"UC-107","parent":"TH-I","kind":"usecase","title":"Lấy dữ liệu thiết bị - Thông số vận hành Kháng điện trạm 110kV","actor":"Kho dữ liệu","flow":["1. Hệ thống yêu cầu kết nối đến Kho dữ liệu. Kho dữ liệu phản hồi thông tin yêu cầu xác thực.","2. Hệ thống gửi thông tin xác thực. Kho dữ liệu xác thực thông tin và phản hồi lại kết quả kết nối: cho phép kết nối nếu xác thực thành công, từ chối mở kết nối nếu không xác thực thành công","3. Hệ thống Lấy dữ liệu thiết bị - Thông số vận hành Kháng điện trạm 110kV. Kho dữ liệu đẩy dữ liệu thiết bị - Thông số vận hành Kháng điện trạm 110kV","4. Hệ thống gửi yêu cầu đóng kết nối tới Kho dữ liệu và lưu thiết bị - Thông số vận hành Kháng điện trạm 110kV vào CSDL"],"tags":["Tích hợp dữ liệu"],"complexity":"medium","transactions":4,"necessity":"B"},
{"sort":123,"code":"UC-108","parent":"TH-I","kind":"usecase","title":"Lấy dữ liệu thiết bị - Thông số vận hành Ắc quy điện trạm 110kV","actor":"Kho dữ liệu","flow":["1. Hệ thống yêu cầu kết nối đến Kho dữ liệu. Kho dữ liệu phản hồi thông tin yêu cầu xác thực.","2. Hệ thống gửi thông tin xác thực. Kho dữ liệu xác thực thông tin và phản hồi lại kết quả kết nối: cho phép kết nối nếu xác thực thành công, từ chối mở kết nối nếu không xác thực thành công","3. Hệ thống Lấy dữ liệu thiết bị - Thông số vận hành Ắc quy điện trạm 110kV. Kho dữ liệu đẩy dữ liệu thiết bị - Thông số vận hành Ắc quy điện trạm 110kV","4. Hệ thống gửi yêu cầu đóng kết nối tới Kho dữ liệu và lưu thiết bị - Thông số vận hành Ắc quy điện trạm 110kV vào CSDL"],"tags":["Tích hợp dữ liệu"],"complexity":"medium","transactions":4,"necessity":"B"},
{"sort":124,"code":"UC-109","parent":"TH-I","kind":"usecase","title":"Lấy dữ liệu thiết bị - Thông số vận hành MBA tự dùng trạm 110kV","actor":"Kho dữ liệu","flow":["1. Hệ thống yêu cầu kết nối đến Kho dữ liệu. Kho dữ liệu phản hồi thông tin yêu cầu xác thực.","2. Hệ thống gửi thông tin xác thực. Kho dữ liệu xác thực thông tin và phản hồi lại kết quả kết nối: cho phép kết nối nếu xác thực thành công, từ chối mở kết nối nếu không xác thực thành công","3. Hệ thống Lấy dữ liệu thiết bị - Thông số vận hành MBA tự dùng trạm 110kV. Kho dữ liệu đẩy dữ liệu thiết bị - Thông số vận hành MBA tự dùng trạm 110kV","4. Hệ thống gửi yêu cầu đóng kết nối tới Kho dữ liệu và lưu thiết bị - Thông số vận hành MBA tự dùng trạm 110kV vào CSDL"],"tags":["Tích hợp dữ liệu"],"complexity":"medium","transactions":4,"necessity":"B"},
{"sort":125,"code":"UC-110","parent":"TH-I","kind":"usecase","title":"Lấy dữ liệu thiết bị - Thông số vận hành Máy cắt trung thế ngoài trời trong TBA 110kV","actor":"Kho dữ liệu","flow":["1. Hệ thống yêu cầu kết nối đến Kho dữ liệu. Kho dữ liệu phản hồi thông tin yêu cầu xác thực.","2. Hệ thống gửi thông tin xác thực. Kho dữ liệu xác thực thông tin và phản hồi lại kết quả kết nối: cho phép kết nối nếu xác thực thành công, từ chối mở kết nối nếu không xác thực thành công","3. Hệ thống Lấy dữ liệu thiết bị - Thông số vận hành Máy cắt trung thế ngoài trời trong TBA 110kV. Kho dữ liệu đẩy dữ liệu thiết bị - Thông số vận hành Máy cắt trung thế ngoài trời trong TBA 110kV","4. Hệ thống gửi yêu cầu đóng kết nối tới Kho dữ liệu và lưu thiết bị - Thông số vận hành Máy cắt trung thế ngoài trời trong TBA 110kV vào CSDL"],"tags":["Tích hợp dữ liệu"],"complexity":"medium","transactions":4,"necessity":"B"},
{"sort":126,"code":"UC-111","parent":"TH-I","kind":"usecase","title":"Lấy dữ liệu thiết bị - Thông số vận hành Dao cách ly trung thế ngoài trời trong TBA 110kV","actor":"Kho dữ liệu","flow":["1. Hệ thống yêu cầu kết nối đến Kho dữ liệu. Kho dữ liệu phản hồi thông tin yêu cầu xác thực.","2. Hệ thống gửi thông tin xác thực. Kho dữ liệu xác thực thông tin và phản hồi lại kết quả kết nối: cho phép kết nối nếu xác thực thành công, từ chối mở kết nối nếu không xác thực thành công","3. Hệ thống Lấy dữ liệu thiết bị - Thông số vận hành Dao cách ly trung thế ngoài trời trong TBA 110kV . Kho dữ liệu đẩy dữ liệu thiết bị - Thông số vận hành Dao cách ly trung thế ngoài trời trong TBA 110kV","4. Hệ thống gửi yêu cầu đóng kết nối tới Kho dữ liệu và lưu thiết bị - Thông số vận hành Dao cách ly trung thế ngoài trời trong TBA 110kV vào CSDL"],"tags":["Tích hợp dữ liệu"],"complexity":"medium","transactions":4,"necessity":"B"},
{"sort":127,"code":"UC-112","parent":"TH-I","kind":"usecase","title":"Lấy dữ liệu thiết bị - Thông số vận hành Chống sét van ĐZ 110kV","actor":"Kho dữ liệu","flow":["1. Hệ thống yêu cầu kết nối đến Kho dữ liệu. Kho dữ liệu phản hồi thông tin yêu cầu xác thực.","2. Hệ thống gửi thông tin xác thực. Kho dữ liệu xác thực thông tin và phản hồi lại kết quả kết nối: cho phép kết nối nếu xác thực thành công, từ chối mở kết nối nếu không xác thực thành công","3. Hệ thống Lấy dữ liệu thiết bị - Thông số vận hành Chống sét van ĐZ 110kV. Kho dữ liệu đẩy dữ liệu thiết bị - Thông số vận hành Chống sét van ĐZ 110kV","4. Hệ thống gửi yêu cầu đóng kết nối tới Kho dữ liệu và lưu thiết bị - Thông số vận hành Chống sét van ĐZ 110kV vào CSDL"],"tags":["Tích hợp dữ liệu"],"complexity":"medium","transactions":4,"necessity":"B"},
{"sort":128,"code":"UC-113","parent":"TH-I","kind":"usecase","title":"Lấy dữ liệu thiết bị - Thông số vận hành Máy biến áp trạm phân phối","actor":"Kho dữ liệu","flow":["1. Hệ thống yêu cầu kết nối đến Kho dữ liệu. Kho dữ liệu phản hồi thông tin yêu cầu xác thực.","2. Hệ thống gửi thông tin xác thực. Kho dữ liệu xác thực thông tin và phản hồi lại kết quả kết nối: cho phép kết nối nếu xác thực thành công, từ chối mở kết nối nếu không xác thực thành công","3. Hệ thống Lấy dữ liệu thiết bị - Thông số vận hành Máy biến áp trạm phân phối. Kho dữ liệu đẩy dữ liệu thiết bị - Thông số vận hành Máy biến áp trạm phân phối","4. Hệ thống gửi yêu cầu đóng kết nối tới Kho dữ liệu và lưu thiết bị - Thông số vận hành Máy biến áp trạm phân phối vào CSDL"],"tags":["Tích hợp dữ liệu"],"complexity":"medium","transactions":4,"necessity":"B"},
{"sort":129,"code":"UC-114","parent":"TH-I","kind":"usecase","title":"Lấy dữ liệu thiết bị - Thông số vận hành Cầu chì tự rơi trạm phân phối","actor":"Kho dữ liệu","flow":["1. Hệ thống yêu cầu kết nối đến Kho dữ liệu. Kho dữ liệu phản hồi thông tin yêu cầu xác thực.","2. Hệ thống gửi thông tin xác thực. Kho dữ liệu xác thực thông tin và phản hồi lại kết quả kết nối: cho phép kết nối nếu xác thực thành công, từ chối mở kết nối nếu không xác thực thành công","3. Hệ thống Lấy dữ liệu thiết bị - Thông số vận hành Cầu chì tự rơi trạm phân phối. Kho dữ liệu đẩy dữ liệu thiết bị - Thông số vận hành Cầu chì tự rơi trạm phân phối","4. Hệ thống gửi yêu cầu đóng kết nối tới Kho dữ liệu và lưu thiết bị - Thông số vận hành Cầu chì tự rơi trạm phân phối vào CSDL"],"tags":["Tích hợp dữ liệu"],"complexity":"medium","transactions":4,"necessity":"B"},
{"sort":130,"code":"UC-115","parent":"TH-I","kind":"usecase","title":"Lấy dữ liệu thiết bị - Thông số vận hành Chống sét van trạm phân phối","actor":"Kho dữ liệu","flow":["1. Hệ thống yêu cầu kết nối đến Kho dữ liệu. Kho dữ liệu phản hồi thông tin yêu cầu xác thực.","2. Hệ thống gửi thông tin xác thực. Kho dữ liệu xác thực thông tin và phản hồi lại kết quả kết nối: cho phép kết nối nếu xác thực thành công, từ chối mở kết nối nếu không xác thực thành công","3. Hệ thống Lấy dữ liệu thiết bị - Thông số vận hành Chống sét van trạm phân phối. Kho dữ liệu đẩy dữ liệu thiết bị - Thông số vận hành Chống sét van trạm phân phối","4. Hệ thống gửi yêu cầu đóng kết nối tới Kho dữ liệu và lưu thiết bị - Thông số vận hành Chống sét van trạm phân phối vào CSDL"],"tags":["Tích hợp dữ liệu"],"complexity":"medium","transactions":4,"necessity":"B"},
{"sort":131,"code":"UC-116","parent":"TH-I","kind":"usecase","title":"Lấy dữ liệu thiết bị - Thông số vận hành Dao cách ly trạm phân phối","actor":"Kho dữ liệu","flow":["1. Hệ thống yêu cầu kết nối đến Kho dữ liệu. Kho dữ liệu phản hồi thông tin yêu cầu xác thực.","2. Hệ thống gửi thông tin xác thực. Kho dữ liệu xác thực thông tin và phản hồi lại kết quả kết nối: cho phép kết nối nếu xác thực thành công, từ chối mở kết nối nếu không xác thực thành công","3. Hệ thống Lấy dữ liệu thiết bị - Thông số vận hành Dao cách ly trạm phân phối. Kho dữ liệu đẩy dữ liệu thiết bị - Thông số vận hành Dao cách ly trạm phân phối","4. Hệ thống gửi yêu cầu đóng kết nối tới Kho dữ liệu và lưu thiết bị - Thông số vận hành Dao cách ly trạm phân phối vào CSDL"],"tags":["Tích hợp dữ liệu"],"complexity":"medium","transactions":4,"necessity":"B"},
{"sort":132,"code":"UC-117","parent":"TH-I","kind":"usecase","title":"Lấy dữ liệu thiết bị - Thông số vận hành Attomat hạ thế trạm phân phối","actor":"Kho dữ liệu","flow":["1. Hệ thống yêu cầu kết nối đến Kho dữ liệu. Kho dữ liệu phản hồi thông tin yêu cầu xác thực.","2. Hệ thống gửi thông tin xác thực. Kho dữ liệu xác thực thông tin và phản hồi lại kết quả kết nối: cho phép kết nối nếu xác thực thành công, từ chối mở kết nối nếu không xác thực thành công","3. Hệ thống Lấy dữ liệu thiết bị - Thông số vận hành Attomat hạ thế trạm phân phối. Kho dữ liệu đẩy dữ liệu thiết bị - Thông số vận hành Attomat hạ thế trạm phân phối","4. Hệ thống gửi yêu cầu đóng kết nối tới Kho dữ liệu và lưu thiết bị - Thông số vận hành Attomat hạ thế trạm phân phối vào CSDL"],"tags":["Tích hợp dữ liệu"],"complexity":"medium","transactions":4,"necessity":"B"},
{"sort":133,"code":"UC-118","parent":"TH-I","kind":"usecase","title":"Lấy dữ liệu thiết bị - Thông số vận hành Tụ bù trạm phân phối","actor":"Kho dữ liệu","flow":["1. Hệ thống yêu cầu kết nối đến Kho dữ liệu. Kho dữ liệu phản hồi thông tin yêu cầu xác thực.","2. Hệ thống gửi thông tin xác thực. Kho dữ liệu xác thực thông tin và phản hồi lại kết quả kết nối: cho phép kết nối nếu xác thực thành công, từ chối mở kết nối nếu không xác thực thành công","3. Hệ thống Lấy dữ liệu thiết bị - Thông số vận hành Tụ bù trạm phân phối. Kho dữ liệu đẩy dữ liệu thiết bị - Thông số vận hành Tụ bù trạm phân phối","4. Hệ thống gửi yêu cầu đóng kết nối tới Kho dữ liệu và lưu thiết bị - Thông số vận hành Tụ bù trạm phân phối vào CSDL"],"tags":["Tích hợp dữ liệu"],"complexity":"medium","transactions":4,"necessity":"B"},
{"sort":134,"code":"UC-119","parent":"TH-I","kind":"usecase","title":"Lấy dữ liệu thiết bị - Thông số vận hành Máy biến dòng điện trạm phân phối","actor":"Kho dữ liệu","flow":["1. Hệ thống yêu cầu kết nối đến Kho dữ liệu. Kho dữ liệu phản hồi thông tin yêu cầu xác thực.","2. Hệ thống gửi thông tin xác thực. Kho dữ liệu xác thực thông tin và phản hồi lại kết quả kết nối: cho phép kết nối nếu xác thực thành công, từ chối mở kết nối nếu không xác thực thành công","3. Hệ thống Lấy dữ liệu thiết bị - Thông số vận hành Máy biến dòng điện trạm phân phối. Kho dữ liệu đẩy dữ liệu thiết bị - Thông số vận hành Máy biến dòng điện trạm phân phối","4. Hệ thống gửi yêu cầu đóng kết nối tới Kho dữ liệu và lưu thiết bị - Thông số vận hành Máy biến dòng điện trạm phân phối vào CSDL"],"tags":["Tích hợp dữ liệu"],"complexity":"medium","transactions":4,"necessity":"B"},
{"sort":135,"code":"UC-120","parent":"TH-I","kind":"usecase","title":"Lấy dữ liệu thiết bị - Thông số vận hành Máy biến điện áp trạm phân phối","actor":"Kho dữ liệu","flow":["1. Hệ thống yêu cầu kết nối đến Kho dữ liệu. Kho dữ liệu phản hồi thông tin yêu cầu xác thực.","2. Hệ thống gửi thông tin xác thực. Kho dữ liệu xác thực thông tin và phản hồi lại kết quả kết nối: cho phép kết nối nếu xác thực thành công, từ chối mở kết nối nếu không xác thực thành công","3. Hệ thống Lấy dữ liệu thiết bị - Thông số vận hành Máy biến điện áp trạm phân phối. Kho dữ liệu đẩy dữ liệu thiết bị - Thông số vận hành Máy biến điện áp trạm phân phối","4. Hệ thống gửi yêu cầu đóng kết nối tới Kho dữ liệu và lưu thiết bị - Thông số vận hành Máy biến điện áp trạm phân phối vào CSDL"],"tags":["Tích hợp dữ liệu"],"complexity":"medium","transactions":4,"necessity":"B"},
{"sort":136,"code":"UC-121","parent":"TH-I","kind":"usecase","title":"Lấy dữ liệu thiết bị - Thông số vận hành Máy cắt Recloser ĐZ TA","actor":"Kho dữ liệu","flow":["1. Hệ thống yêu cầu kết nối đến Kho dữ liệu. Kho dữ liệu phản hồi thông tin yêu cầu xác thực.","2. Hệ thống gửi thông tin xác thực. Kho dữ liệu xác thực thông tin và phản hồi lại kết quả kết nối: cho phép kết nối nếu xác thực thành công, từ chối mở kết nối nếu không xác thực thành công","3. Hệ thống Lấy dữ liệu thiết bị - Thông số vận hành Máy cắt Recloser ĐZ TA. Kho dữ liệu đẩy dữ liệu thiết bị - Thông số vận hành Máy cắt Recloser ĐZ TA","4. Hệ thống gửi yêu cầu đóng kết nối tới Kho dữ liệu và lưu thiết bị - Thông số vận hành Máy cắt Recloser ĐZ TA vào CSDL"],"tags":["Tích hợp dữ liệu"],"complexity":"medium","transactions":4,"necessity":"B"},
{"sort":137,"code":"UC-122","parent":"TH-I","kind":"usecase","title":"Lấy dữ liệu thiết bị - Thông số vận hành Cầu dao cáo điều khiển ĐZ TA","actor":"Kho dữ liệu","flow":["1. Hệ thống yêu cầu kết nối đến Kho dữ liệu. Kho dữ liệu phản hồi thông tin yêu cầu xác thực.","2. Hệ thống gửi thông tin xác thực. Kho dữ liệu xác thực thông tin và phản hồi lại kết quả kết nối: cho phép kết nối nếu xác thực thành công, từ chối mở kết nối nếu không xác thực thành công","3. Hệ thống Lấy dữ liệu thiết bị - Thông số vận hành Cầu dao cáo điều khiển ĐZ TA. Kho dữ liệu đẩy dữ liệu thiết bị - Thông số vận hành Cầu dao cáo điều khiển ĐZ TA","4. Hệ thống gửi yêu cầu đóng kết nối tới Kho dữ liệu và lưu thiết bị - Thông số vận hành Cầu dao cáo điều khiển ĐZ TA vào CSDL"],"tags":["Tích hợp dữ liệu"],"complexity":"medium","transactions":4,"necessity":"B"},
{"sort":138,"code":"UC-123","parent":"TH-I","kind":"usecase","title":"Lấy dữ liệu thiết bị - Thông số vận hành Dao cách ly ĐZ TA","actor":"Kho dữ liệu","flow":["1. Hệ thống yêu cầu kết nối đến Kho dữ liệu. Kho dữ liệu phản hồi thông tin yêu cầu xác thực.","2. Hệ thống gửi thông tin xác thực. Kho dữ liệu xác thực thông tin và phản hồi lại kết quả kết nối: cho phép kết nối nếu xác thực thành công, từ chối mở kết nối nếu không xác thực thành công","3. Hệ thống Lấy dữ liệu thiết bị - Thông số vận hành Dao cách ly ĐZ TA. Kho dữ liệu đẩy dữ liệu thiết bị - Thông số vận hành Dao cách ly ĐZ TA","4. Hệ thống gửi yêu cầu đóng kết nối tới Kho dữ liệu và lưu thiết bị - Thông số vận hành Dao cách ly ĐZ TA vào CSDL"],"tags":["Tích hợp dữ liệu"],"complexity":"medium","transactions":4,"necessity":"B"},
{"sort":139,"code":"UC-124","parent":"TH-I","kind":"usecase","title":"Lấy dữ liệu thiết bị - Thông số vận hành Cầu chì tự rơi ĐZ TA","actor":"Kho dữ liệu","flow":["1. Hệ thống yêu cầu kết nối đến Kho dữ liệu. Kho dữ liệu phản hồi thông tin yêu cầu xác thực.","2. Hệ thống gửi thông tin xác thực. Kho dữ liệu xác thực thông tin và phản hồi lại kết quả kết nối: cho phép kết nối nếu xác thực thành công, từ chối mở kết nối nếu không xác thực thành công","3. Hệ thống Lấy dữ liệu thiết bị - Thông số vận hành Cầu chì tự rơi ĐZ TA. Kho dữ liệu đẩy dữ liệu thiết bị - Thông số vận hành Cầu chì tự rơi ĐZ TA","4. Hệ thống gửi yêu cầu đóng kết nối tới Kho dữ liệu và lưu thiết bị - Thông số vận hành Cầu chì tự rơi ĐZ TA vào CSDL"],"tags":["Tích hợp dữ liệu"],"complexity":"medium","transactions":4,"necessity":"B"},
{"sort":140,"code":"UC-125","parent":"TH-I","kind":"usecase","title":"Lấy dữ liệu thiết bị - Thông số vận hành Tủ RMU ĐZ TA","actor":"Kho dữ liệu","flow":["1. Hệ thống yêu cầu kết nối đến Kho dữ liệu. Kho dữ liệu phản hồi thông tin yêu cầu xác thực.","2. Hệ thống gửi thông tin xác thực. Kho dữ liệu xác thực thông tin và phản hồi lại kết quả kết nối: cho phép kết nối nếu xác thực thành công, từ chối mở kết nối nếu không xác thực thành công","3. Hệ thống Lấy dữ liệu thiết bị - Thông số vận hành Tủ RMU ĐZ TA. Kho dữ liệu đẩy dữ liệu thiết bị - Thông số vận hành Tủ RMU ĐZ TA","4. Hệ thống gửi yêu cầu đóng kết nối tới Kho dữ liệu và lưu thiết bị - Thông số vận hành Tủ RMU ĐZ TA vào CSDL"],"tags":["Tích hợp dữ liệu"],"complexity":"medium","transactions":4,"necessity":"B"},
{"sort":141,"code":"UC-126","parent":"TH-I","kind":"usecase","title":"Lấy dữ liệu thiết bị - Thông số vận hành Chống sét van ĐZ TA","actor":"Kho dữ liệu","flow":["1. Hệ thống yêu cầu kết nối đến Kho dữ liệu. Kho dữ liệu phản hồi thông tin yêu cầu xác thực.","2. Hệ thống gửi thông tin xác thực. Kho dữ liệu xác thực thông tin và phản hồi lại kết quả kết nối: cho phép kết nối nếu xác thực thành công, từ chối mở kết nối nếu không xác thực thành công","3. Hệ thống Lấy dữ liệu thiết bị - Thông số vận hành Chống sét van ĐZ TA. Kho dữ liệu đẩy dữ liệu thiết bị - Thông số vận hành Chống sét van ĐZ TA","4. Hệ thống gửi yêu cầu đóng kết nối tới Kho dữ liệu và lưu thiết bị - Thông số vận hành Chống sét van ĐZ TA vào CSDL"],"tags":["Tích hợp dữ liệu"],"complexity":"medium","transactions":4,"necessity":"B"},
{"sort":142,"code":"UC-127","parent":"TH-I","kind":"usecase","title":"Lấy dữ liệu kiểm định VTTB","actor":"Kho dữ liệu","flow":["1. Hệ thống yêu cầu kết nối đến Kho dữ liệu. Kho dữ liệu phản hồi thông tin yêu cầu xác thực.","2. Hệ thống gửi thông tin xác thực. Kho dữ liệu xác thực thông tin và phản hồi lại kết quả kết nối: cho phép kết nối nếu xác thực thành công, từ chối mở kết nối nếu không xác thực thành công","3. Hệ thống Lấy dữ liệu kiểm định VTTB. Kho dữ liệu đẩy dữ liệu kiểm định VTTB","4. Hệ thống gửi yêu cầu đóng kết nối tới Kho dữ liệu và lưu kiểm định VTTB vào CSDL"],"tags":["Tích hợp dữ liệu"],"complexity":"medium","transactions":4,"necessity":"B"},
{"sort":143,"code":"UC-128","parent":"TH-I","kind":"usecase","title":"Lấy dữ liệu mapping đơn vị, lộ, trạm","actor":"Kho dữ liệu","flow":["1. Hệ thống yêu cầu kết nối đến Kho dữ liệu. Kho dữ liệu phản hồi thông tin yêu cầu xác thực.","2. Hệ thống gửi thông tin xác thực. Kho dữ liệu xác thực thông tin và phản hồi lại kết quả kết nối: cho phép kết nối nếu xác thực thành công, từ chối mở kết nối nếu không xác thực thành công","3. Hệ thống Lấy dữ liệu mapping đơn vị, lộ, trạm. Kho dữ liệu đẩy dữ liệu mapping đơn vị, lộ, trạm","4. Hệ thống gửi yêu cầu đóng kết nối tới Kho dữ liệu và lưu mapping đơn vị, lộ, trạm vào CSDL"],"tags":["Tích hợp dữ liệu"],"complexity":"medium","transactions":4,"necessity":"B"},
{"sort":144,"code":"UC-129","parent":"TH-I","kind":"usecase","title":"Lấy dữ liệu vị trí của VTTB","actor":"Kho dữ liệu","flow":["1. Hệ thống yêu cầu kết nối đến Kho dữ liệu. Kho dữ liệu phản hồi thông tin yêu cầu xác thực.","2. Hệ thống gửi thông tin xác thực. Kho dữ liệu xác thực thông tin và phản hồi lại kết quả kết nối: cho phép kết nối nếu xác thực thành công, từ chối mở kết nối nếu không xác thực thành công","3. Hệ thống Lấy dữ liệu vị trí của VTTB. Kho dữ liệu đẩy dữ liệu vị trí của VTTB","4. Hệ thống gửi yêu cầu đóng kết nối tới Kho dữ liệu và lưu vị trí của VTTB vào CSDL"],"tags":["Tích hợp dữ liệu"],"complexity":"medium","transactions":4,"necessity":"B"},
{"sort":145,"code":"UC-130","parent":"TH-I","kind":"usecase","title":"Lấy dữ liệu sự cố của VTTB","actor":"Kho dữ liệu","flow":["1. Hệ thống yêu cầu kết nối đến Kho dữ liệu. Kho dữ liệu phản hồi thông tin yêu cầu xác thực.","2. Hệ thống gửi thông tin xác thực. Kho dữ liệu xác thực thông tin và phản hồi lại kết quả kết nối: cho phép kết nối nếu xác thực thành công, từ chối mở kết nối nếu không xác thực thành công","3. Hệ thống Lấy dữ liệu sự cố của VTTB. Kho dữ liệu đẩy dữ liệu sự cố của VTTB","4. Hệ thống gửi yêu cầu đóng kết nối tới Kho dữ liệu và lưu sự cố của VTTB vào CSDL"],"tags":["Tích hợp dữ liệu"],"complexity":"medium","transactions":4,"necessity":"B"},
{"sort":146,"code":"UC-131","parent":"TH-I","kind":"usecase","title":"Lấy dữ liệu hư hỏng của VTTB","actor":"Kho dữ liệu","flow":["1. Hệ thống yêu cầu kết nối đến Kho dữ liệu. Kho dữ liệu phản hồi thông tin yêu cầu xác thực.","2. Hệ thống gửi thông tin xác thực. Kho dữ liệu xác thực thông tin và phản hồi lại kết quả kết nối: cho phép kết nối nếu xác thực thành công, từ chối mở kết nối nếu không xác thực thành công","3. Hệ thống Lấy dữ liệu hư hỏng của VTTB. Kho dữ liệu đẩy dữ liệu hư hỏng của VTTB","4. Hệ thống gửi yêu cầu đóng kết nối tới Kho dữ liệu và lưu hư hỏng của VTTB vào CSDL"],"tags":["Tích hợp dữ liệu"],"complexity":"medium","transactions":4,"necessity":"B"},
{"sort":147,"code":"UC-132","parent":"TH-I","kind":"usecase","title":"Lấy dữ liệu VTTB ngoài lưới","actor":"Kho dữ liệu","flow":["1. Hệ thống yêu cầu kết nối đến Kho dữ liệu. Kho dữ liệu phản hồi thông tin yêu cầu xác thực.","2. Hệ thống gửi thông tin xác thực. Kho dữ liệu xác thực thông tin và phản hồi lại kết quả kết nối: cho phép kết nối nếu xác thực thành công, từ chối mở kết nối nếu không xác thực thành công","3. Hệ thống Lấy dữ liệu VTTB ngoài lưới. Kho dữ liệu đẩy dữ liệu VTTB ngoài lưới","4. Hệ thống gửi yêu cầu đóng kết nối tới Kho dữ liệu và lưu VTTB ngoài lưới vào CSDL"],"tags":["Tích hợp dữ liệu"],"complexity":"medium","transactions":4,"necessity":"B"},
{"sort":148,"code":"UC-133","parent":"TH-I","kind":"usecase","title":"Lấy dữ liệu VTTB trên lưới","actor":"Kho dữ liệu","flow":["1. Hệ thống yêu cầu kết nối đến Kho dữ liệu. Kho dữ liệu phản hồi thông tin yêu cầu xác thực.","2. Hệ thống gửi thông tin xác thực. Kho dữ liệu xác thực thông tin và phản hồi lại kết quả kết nối: cho phép kết nối nếu xác thực thành công, từ chối mở kết nối nếu không xác thực thành công","3. Hệ thống Lấy dữ liệu VTTB trên lưới. Kho dữ liệu đẩy dữ liệu VTTB trên lưới","4. Hệ thống gửi yêu cầu đóng kết nối tới Kho dữ liệu và lưu VTTB trên lưới vào CSDL"],"tags":["Tích hợp dữ liệu"],"complexity":"medium","transactions":4,"necessity":"B"}]
$json$::jsonb)
        as x(sort integer, code text, parent text, kind text, title text, actor text, flow jsonb, tags jsonb,
             complexity text, transactions integer, necessity text)
     order by sort
  loop
    v_parent := null;
    if r.parent is not null then
      select id into v_parent from public.use_cases where project_id = v_project and code = r.parent;
      if v_parent is null then
        raise exception 'Không tìm thấy use case cha % của %', r.parent, r.code;
      end if;
    end if;

    insert into public.use_cases
      (project_id, parent_id, code, title, actor, main_flow, kind, tags, complexity, transactions, necessity)
    values
      (v_project, v_parent, r.code, r.title, coalesce(r.actor, ''),
       array(select jsonb_array_elements_text(r.flow)),
       r.kind, array(select jsonb_array_elements_text(r.tags)), r.complexity, r.transactions, coalesce(r.necessity, 'B'))
    on conflict (project_id, code) do update
      set parent_id = excluded.parent_id,
          title = excluded.title,
          actor = excluded.actor,
          main_flow = excluded.main_flow,
          kind = excluded.kind,
          tags = excluded.tags,
          complexity = excluded.complexity,
          transactions = excluded.transactions,
          necessity = excluded.necessity
    returning (xmax = 0) into v_new;

    if v_new then n_new := n_new + 1; else n_upd := n_upd + 1; end if;
  end loop;

  raise notice 'Nhập xong: % use case/nhóm mới, % cập nhật.', n_new, n_upd;
end
$import$;

-- Kiểm tra nhanh: kỳ vọng 2 nhóm và 77 use case.
select kind, count(*) as so_luong
  from public.use_cases
 where project_id = (select id from public.projects where code = 'GPDN_DNMB_EVNNPC_QTVT_251004')
   and code in ('TH', 'TH-I', 'UC-057', 'UC-058', 'UC-059', 'UC-060', 'UC-061', 'UC-062', 'UC-063', 'UC-064', 'UC-065', 'UC-066', 'UC-067', 'UC-068', 'UC-069', 'UC-070', 'UC-071', 'UC-072', 'UC-073', 'UC-074', 'UC-075', 'UC-076', 'UC-077', 'UC-078', 'UC-079', 'UC-080', 'UC-081', 'UC-082', 'UC-083', 'UC-084', 'UC-085', 'UC-086', 'UC-087', 'UC-088', 'UC-089', 'UC-090', 'UC-091', 'UC-092', 'UC-093', 'UC-094', 'UC-095', 'UC-096', 'UC-097', 'UC-098', 'UC-099', 'UC-100', 'UC-101', 'UC-102', 'UC-103', 'UC-104', 'UC-105', 'UC-106', 'UC-107', 'UC-108', 'UC-109', 'UC-110', 'UC-111', 'UC-112', 'UC-113', 'UC-114', 'UC-115', 'UC-116', 'UC-117', 'UC-118', 'UC-119', 'UC-120', 'UC-121', 'UC-122', 'UC-123', 'UC-124', 'UC-125', 'UC-126', 'UC-127', 'UC-128', 'UC-129', 'UC-130', 'UC-131', 'UC-132', 'UC-133')
 group by kind
 order by kind;
