-- Nhập danh sách Use Case dự án GPDN_DNMB_EVNNPC_QTVT_251004 - phần Văn phòng
-- Nguồn: Danh sách chức năng điều chỉnh BCC Vật tư_0508.xlsx (sheet UC sau điều chỉnh final)
-- Gồm 13 module/nhóm (kind = group) và 23 use case (kind = usecase), cây tối đa 3 cấp.
-- Sinh tự động bởi scripts/gen-usecase-import.py - đừng sửa tay, hãy sửa Excel rồi sinh lại.
--
-- Chạy SAU migration 0009_usecase_attributes.sql, trong Supabase SQL Editor.
-- An toàn khi chạy lại: khớp theo (dự án, mã); chỉ cập nhật tên/tác nhân/luồng/nhãn/độ phức tạp/transaction,
-- KHÔNG ghi đè trạng thái, tiến độ, người phụ trách, mô tả hay tiêu chí nghiệm thu đã nhập tay.
-- Hoàn tác: chạy qtvt_usecases_rollback.sql.

do $import$
declare
  v_project_code constant text := 'GPDN_DNMB_EVNNPC_QTVT_251004';
  v_project uuid;
  r record;
  v_parent uuid;
  v_new boolean;
  n_new integer := 0;
  n_upd integer := 0;
begin
  select id into v_project from public.projects where code = v_project_code;
  if v_project is null then
    raise exception 'Không tìm thấy dự án có mã %. Kiểm tra lại mã dự án.', v_project_code;
  end if;

  for r in
    select *
      from jsonb_to_recordset($json$[{"sort":149,"code":"VP-I","parent":null,"kind":"group","title":"Quản lý danh mục hàng hóa","actor":"","flow":[],"tags":["Văn phòng"],"complexity":null,"transactions":null,"necessity":"B"},
{"sort":150,"code":"UC-134","parent":"VP-I","kind":"usecase","title":"Quản lý danh mục vật tư, thiết bị Văn phòng","actor":"Quản trị phần mềm","flow":["1. Quản trị phần mềm thêm mới danh mục vật tư, thiết bị Văn phòng trên giao diện. Hệ thống lưu danh mục vật tư, thiết bị Văn phòng được thêm mới","2. Quản trị phần mềm thực hiện import file excel danh mục vật tư, thiết bị Văn phòng theo biểu mẫu. Hệ thống đọc thông tin danh mục vật tư, thiết bị Văn phòng trong file import và lưu vào CSDL","3. Quản trị phần mềm thực hiện chỉnh sửa danh mục vật tư, thiết bị Văn phòng. Hệ thống lưu danh mục vật tư, thiết bị Văn phòng do người dùng chỉnh sửa","4. Quản trị phần mềm thực hiện chọn và xóa một hoặc một số danh mục vật tư, thiết bị Văn phòng. Hệ thống kiểm tra điều kiện ràng buộc và xóa thông tin theo yêu cầu người dùng","5. Quản trị phần mềm tìm kiếm danh mục vật tư, thiết bị Văn phòng. Hệ thống tìm kiếm và trả kết quả cho người dùng","6. Quản trị phần mềm xem chi tiết danh mục vật tư, thiết bị Văn phòng. Hệ thống hiển thị chi tiết danh mục vật tư, thiết bị Văn phòng"],"tags":["Văn phòng"],"complexity":"medium","transactions":6,"necessity":"B"},
{"sort":151,"code":"VP-II","parent":null,"kind":"group","title":"Yêu cầu mua sắm","actor":"","flow":[],"tags":["Văn phòng"],"complexity":null,"transactions":null,"necessity":"B"},
{"sort":152,"code":"UC-135","parent":"VP-II","kind":"usecase","title":"Quản lý yêu cầu đăng ký, cấp mới vật tư, thiết bị Văn phòng","actor":"Chuyên viên Ban chuyên môn","flow":["1. Chuyên viên Ban chuyên môn thêm mới yêu cầu đăng ký, cấp mới vật tư, thiết bị Văn phòng trên giao diện. Hệ thống lưuu yêu cầu đăng ký, cấp mới vật tư, thiết bị Văn phòng được thêm mới","2. Chuyên viên Ban chuyên môn thực hiện import file excel yêu cầu đăng ký, cấp mới vật tư, thiết bị Văn phòng theo biểu mẫu. Hệ thống đọc thông tin yêu cầu đăng ký, cấp mới vật tư, thiết bị Văn phòng trong file import và lưu vào CSDL","3. Chuyên viên Ban chuyên môn thực hiện chỉnh sửa yêu cầu đăng ký, cấp mới vật tư, thiết bị Văn phòng chưa trình phê duyệt. Hệ thống lưu yêu cầu đăng ký, cấp mới vật tư, thiết bị Văn phòng do người dùng chỉnh sửa","4. Chuyên viên Ban chuyên môn thực hiện chọn và xóa một hoặc một số yêu cầu đăng ký, cấp mới vật tư, thiết bị Văn phòng. Hệ thống kiểm tra điều kiện ràng buộc và xóa thông tin theo yêu cầu người dùng","5. Chuyên viên Ban chuyên môn tìm kiếm yêu cầu đăng ký, cấp mới vật tư, thiết bị Văn phòng. Hệ thống tìm kiếm và trả kết quả cho người dùng","6. Chuyên viên Ban chuyên môn xem chi tiết yêu cầu đăng ký, cấp mới vật tư, thiết bị Văn phòng. Hệ thống hiển thị chi tiết yêu cầu đăng ký, cấp mới vật tư, thiết bị Văn phòng","7. Chuyên viên Ban chuyên môn thực hiện chức năng xuất file yêu cầu đăng ký, cấp mới vật tư, thiết bị Văn phòng .Hệ thống thực hiện xuất file theo định dạng pdf","8. Chuyên viên Ban chuyên môn thực hiện chuyển yêu cầu đăng ký, cấp mới vật tư, thiết bị Văn phòng đã được lãnh đạo Ban phê duyệt sang Văn Phòng. Hệ thống chuyển file yêu cầu đăng ký, cấp mới vật tư, thiết bị Văn phòng cho Văn Phòng","9. Chuyên viên Văn phòng thực hiện tiếp nhận yêu cầu đăng ký, cấp mới vật tư, thiết bị Văn phòng"],"tags":["Văn phòng"],"complexity":"complex","transactions":9,"necessity":"B"},
{"sort":153,"code":"UC-136","parent":"VP-II","kind":"usecase","title":"Tổng hợp yêu cầu mua sắm vật tư tiêu, thiết bị Văn Phòng","actor":"Chuyên viên Văn phòng","flow":["1. Chuyên viên Văn phòng xem Tổng hợp yêu cầu mua sắm vật tư tiêu, thiết bị Văn Phòng. Hệ thống thực hiện Tổng hợp yêu cầu mua sắm vật tư tiêu, thiết bị Văn Phòng của các Ban chuyên môn","2. Chuyên viên Văn phòng tìm kiếm Tổng hợp yêu cầu mua sắm vật tư tiêu, thiết bị Văn Phòng yêu cầu mua sắm vật tư tiêu, thiết bị Văn Phòng. Hệ thống tìm kiếm theo yêu cầu của Chuyên viên Văn phòng","3. Chuyên viên Văn phòng điều chỉnh Tổng hợp yêu cầu mua sắm vật tư tiêu, thiết bị Văn Phòng sau khi hệ thống tổng hợp. Hệ thống lưu thông tin do Chuyên viên Văn phòng chỉnh sửa","4. Chuyên viên Văn phòng xuất dữ liệu Tổng hợp yêu cầu mua sắm vật tư tiêu, thiết bị Văn Phòng ra file excel. Hệ thống xuất dữ liệu theo yêu cầu.","5. Chuyên viên văn phòng gửi trình phê duyệt tổng hợp yêu cầu mua sắm đến Lãnh đạo Văn phòng","6. Lãnh đạo văn phòng phê duyệt/ Từ chối phê duyệt tổng hợp yêu cầu mua sắm"],"tags":["Văn phòng"],"complexity":"medium","transactions":6,"necessity":"B"},
{"sort":154,"code":"VP-III","parent":null,"kind":"group","title":"Tiếp nhận","actor":"","flow":[],"tags":["Văn phòng"],"complexity":null,"transactions":null,"necessity":"B"},
{"sort":155,"code":"UC-137","parent":"VP-III","kind":"usecase","title":"Quản lý tiếp nhận vật tư, thiết bị Văn phòng","actor":"Người sử dụng","flow":["1. Người sử dụng thêm mới tiếp nhận vật tư, thiết bị Văn phòng trên giao diện. Hệ thống lưuu tiếp nhận vật tư, thiết bị Văn phòng được thêm mới","2. Người sử dụng thực hiện chỉnh sửa tiếp nhận vật tư, thiết bị Văn phòng. Hệ thống lưu tiếp nhận vật tư, thiết bị Văn phòng do người dùng chỉnh sửa","3. Người sử dụng thực hiện chọn và xóa một hoặc một số tiếp nhận vật tư, thiết bị Văn phòng. Hệ thống kiểm tra điều kiện ràng buộc và xóa thông tin theo yêu cầu người dùng","4. Người sử dụng tìm kiếm tiếp nhận vật tư, thiết bị Văn phòng. Hệ thống tìm kiếm và trả kết quả cho người dùng","5. Người sử dụng xem chi tiết tiếp nhận vật tư, thiết bị Văn phòng. Hệ thống hiển thị chi tiết tiếp nhận vật tư, thiết bị Văn phòng","6. Người sử dụng xuất phiếu tiếp nhận ra file excel"],"tags":["Văn phòng"],"complexity":"medium","transactions":6,"necessity":"B"},
{"sort":156,"code":"VP-IV","parent":null,"kind":"group","title":"Cấp phát","actor":"","flow":[],"tags":["Văn phòng"],"complexity":null,"transactions":null,"necessity":"B"},
{"sort":157,"code":"UC-138","parent":"VP-IV","kind":"usecase","title":"Quản lý cấp phát","actor":"Chuyên viên Văn phòng/ NPCIT/ Chuyên viên Ban chuyên môn","flow":["1. Chuyên viên Văn phòng/ NPCIT/ Chuyên viên Ban chuyên môn thêm mới cấp phát trên giao diện. Hệ thống lưu cấp phát được thêm mới","2. Chuyên viên Văn phòng/ NPCIT/ Chuyên viên Ban chuyên môn thực hiện chỉnh sửa cấp phát. Hệ thống lưu cấp phát do người dùng chỉnh sửa","3. Chuyên viên Văn phòng/ NPCIT/ Chuyên viên Ban chuyên môn thực hiện chọn và xóa một hoặc một số cấp phát. Hệ thống kiểm tra điều kiện ràng buộc và xóa thông tin theo yêu cầu người dùng","4. Chuyên viên Văn phòng/ NPCIT/ Chuyên viên Ban chuyên môn tìm kiếm cấp phát. Hệ thống tìm kiếm và trả kết quả cho người dùng","5. Chuyên viên Văn phòng/ NPCIT/ Chuyên viên Ban chuyên môn xem chi tiết cấp phát. Hệ thống hiển thị chi tiết cấp phát","6. Chuyên viên Văn phòng/ NPCIT/ Chuyên viên Ban chuyên môn xuất dữ liệu cấp phát ra file excel. Hệ thống xuất dữ liệu theo yêu cầu"],"tags":["Văn phòng"],"complexity":"medium","transactions":6,"necessity":"B"},
{"sort":158,"code":"VP-V","parent":null,"kind":"group","title":"Điều chuyển","actor":"","flow":[],"tags":["Văn phòng"],"complexity":null,"transactions":null,"necessity":"B"},
{"sort":159,"code":"UC-139","parent":"VP-V","kind":"usecase","title":"Quản lý điều chuyển","actor":"Người sử dụng","flow":["1. Chuyên viên Ban chuyên môn tạo yêu cầu điều chuyển theo nội bộ hoặc điều chuyển ngoài điều chuyển trên giao diện. Hệ thống lưu điều chuyển được thêm mới","2. Chuyên viên Ban chuyên môn thực hiện chỉnh sửa điều chuyển. Hệ thống lưu điều chuyển do người dùng chỉnh sửa","3. Chuyên viên Ban chuyên môn thực hiện chọn và xóa một hoặc một số điều chuyển. Hệ thống kiểm tra điều kiện ràng buộc và xóa thông tin theo yêu cầu người dùng","4. Chuyên viên Ban chuyên môn gửi yêu cầu điều chuyển điều chuyển tới cấp có thẩm quyền. Hệ thống gửi thông báo tới lãnh đạo","5. Lãnh đạo thực hiện xác nhận hoặc từ chối yêu cầu điều chuyển. Hệ thống nhận kết quả trả về và gửi lại thông báo","6. Chuyên viên Ban chuyên môn tìm kiếm điều chuyển. Hệ thống tìm kiếm và trả kết quả cho người dùng","7. Chuyên viên Ban chuyên môn xem chi tiết điều chuyển. Hệ thống hiển thị chi tiết điều chuyển"],"tags":["Văn phòng"],"complexity":"medium","transactions":7,"necessity":"B"},
{"sort":160,"code":"VP-VI","parent":null,"kind":"group","title":"Kiểm kê","actor":"","flow":[],"tags":["Văn phòng"],"complexity":null,"transactions":null,"necessity":"B"},
{"sort":161,"code":"UC-140","parent":"VP-VI","kind":"usecase","title":"Yêu cầu kiểm kê","actor":"Chuyên viên Văn phòng","flow":["1. Chuyên viên Văn phòng tạo yêu cầu kiểm kê trên giao diện. Hệ thống lưu thông tin kiểm kê được yêu cầu","2. Chuyên viên Văn phòng thực hiện chỉnh sửa yêu cầu kiểm kê. Hệ thống lưu thông tin kiểm kê do người dùng chỉnh sửa","3. Chuyên viên Văn phòng thực hiện chọn và xóa một hoặc một số kiểm kê. Hệ thống kiểm tra điều kiện ràng buộc và xóa thông tin theo yêu cầu người dùng","4. Chuyên viên Văn phòng tìm kiếm kiểm kê. Hệ thống tìm kiếm và trả kết quả cho người dùng","5. Chuyên viên Văn phòng xem chi tiết kiểm kê. Hệ thống hiển thị chi tiết kiểm kê","6. Chuyên viên Văn phòng chuyển yêu cầu kiểm kê tới Ban chuyên môn. Hệ thống gửi thông báo tới Ban chuyên môn"],"tags":["Văn phòng"],"complexity":"medium","transactions":6,"necessity":"B"},
{"sort":162,"code":"UC-141","parent":"VP-VI","kind":"usecase","title":"Tiếp nhận yêu cầu kiểm kê","actor":"Chuyên viên Ban chuyên môn, Lãnh đạo Ban chuyên môn","flow":["1. Chuyên viên Ban chuyên môn tiếp nhận yêu cầu kiểm kê. Hệ thống gửi thông báo về yêu cầu kiểm kê","2. Chuyên viên Ban chuyên môn thực hiện import file kiểm kê. Hệ thống thực hiện import file theo yêu cầu","3. Chuyên viên Ban chuyên môn tìm kiếm thông tin kiểm kê. Hệ thống tìm kiếm và trả kết quả cho người dùng","4. Chuyên viên Ban chuyên môn xem chi tiết thông tin kiểm kê. Hệ thống hiển thị chi tiết kiểm kê","5. Chuyên viên Ban chuyên môn trình ký thông tin kiểm kê tới lãnh đạo Ban. Hệ thống chuyển file trình ký dạng pdf tới cấp được trình ký","6. Lãnh đạo Ban thực hiện phê duyệt hoặc từ chối nội dung trình ký. Hệ thống nhận kết quả và trả và gửi lại thông báo","7. Chuyên viên Ban chuyên môn chuyển file kiểm kê đã được lãnh đạo ký gửi tới Văn phòng. Hệ thống thực hiện chuyển file kiểm kê tới Văn phòng"],"tags":["Văn phòng"],"complexity":"medium","transactions":7,"necessity":"B"},
{"sort":163,"code":"VP-VII","parent":null,"kind":"group","title":"Bảo trì, bảo dưỡng","actor":"","flow":[],"tags":["Văn phòng"],"complexity":null,"transactions":null,"necessity":"B"},
{"sort":164,"code":"UC-142","parent":"VP-VII","kind":"usecase","title":"Yêu cầu bảo trì, bảo dưỡng","actor":"Chuyên viên Ban chuyên môn","flow":["1. Chuyên viên Ban chuyên môn tạo yêu cầu bảo trì, bảo dưỡng trên giao diện. Hệ thống lưu bảo trì, bảo dưỡng được thêm mới","2. Chuyên viên Ban chuyên môn thực hiện chỉnh sửa bảo trì, bảo dưỡng chưa trình phê duyệt. Hệ thống lưu bảo trì, bảo dưỡng do người dùng chỉnh sửa","3. Chuyên viên Ban chuyên môn thực hiện chọn và xóa một hoặc một số bảo trì, bảo dưỡng. Hệ thống kiểm tra điều kiện ràng buộc và xóa thông tin theo yêu cầu người dùng","4. Chuyên viên Ban chuyên môn gửi một hoặc nhiều Yêu cầu bảo trì, bảo dưỡng .Hệ thống gửi thông tin đến Văn phòng.","5. Lãnh đạo ban chuyên môn phê duyệt/ Từ chối một hoặc nhiều yêu cầu bảo trì, bảo dưỡng","6. Chuyên viên Văn phòng tiếp nhận một hoặc nhiều bảo trì, bảo dưỡng Hệ thống lưu kết quả tiếp nhận và chuyển bảo trì, bảo dưỡng đến Chuyên viên Ban chuyên môn","7. Chuyên viên Ban chuyên môn tìm kiếm bảo trì, bảo dưỡng. Hệ thống tìm kiếm và trả kết quả cho người dùng","8. Chuyên viên Ban chuyên môn xem chi tiết bảo trì, bảo dưỡng. Hệ thống hiển thị chi tiết bảo trì, bảo dưỡng"],"tags":["Văn phòng"],"complexity":"complex","transactions":8,"necessity":"B"},
{"sort":165,"code":"UC-143","parent":"VP-VII","kind":"usecase","title":"Tiếp nhận yêu cầu bảo trì, bảo dưỡng vật tư, thiết bị","actor":"Văn phòng","flow":["1. Văn phòng tiếp nhận một hoặc nhiều yêu cầu bảo trì, bảo dưỡng vật tư, thiết bị .Hệ thống gửi thông báo Tiếp nhận yêu cầu bảo trì, bảo dưỡng vật tư, thiết bị tới Văn phòng","2. Văn phòng tìm kiếm yêu cầu bảo trì, bảo dưỡng vật tư, thiết bị. Hệ thống tìm kiếm và trả kết quả cho người dùng","3. Văn phòng xem chi tiết yêu cầu bảo trì, bảo dưỡng vật tư, thiết bị. Hệ thống hiển thị chi tiết yêu cầu bảo trì, bảo dưỡng vật tư, thiết bị","4. Văn phòng phân công yêu cầu bảo trì, bảo dưỡng vật tư, thiết bị tới Ban tiếp nhận. Hệ thống gửi thông báoyêu cầu bảo trì, bảo dưỡng vật tư, thiết bị tới đầu mối tiếp nhận"],"tags":["Văn phòng"],"complexity":"medium","transactions":4,"necessity":"B"},
{"sort":166,"code":"VP-VIII","parent":null,"kind":"group","title":"Đánh giá lại","actor":"","flow":[],"tags":["Văn phòng"],"complexity":null,"transactions":null,"necessity":"B"},
{"sort":167,"code":"UC-144","parent":"VP-VIII","kind":"usecase","title":"Quản lý đánh giá lại","actor":"Người sử dụng","flow":["1. Chuyên viên ban chuyên môn chọn chức năng đánh giá lại. Hệ thống hiển thị danh sách gợi ý tài sản cần đánh giá lại","2. Chuyên viên ban chuyên môn thực hiện thêm mới thông tin đánh giá lại. Hệ thống lưu thông tin đánh giá lại được yêu cầu","3. Chuyên viên ban chuyên môn thực hiện chỉnh sửa yêu cầu đánh giá lại. Hệ thống lưu thông tin đánh giá lại do người dùng chỉnh sửa","4. Chuyên viên ban chuyên môn thực hiện chọn và xóa một hoặc một số đánh giá lại. Hệ thống kiểm tra điều kiện ràng buộc và xóa thông tin theo yêu cầu người dùng","5. Chuyên viên ban chuyên môn tìm kiếm đánh giá lại. Hệ thống tìm kiếm và trả kết quả cho người dùng","6. Chuyên viên ban chuyên môn xem chi tiết đánh giá lại. Hệ thống hiển thị chi tiết đánh giá lại","7. Chuyên viên ban chuyên môn gửi trình phê duyệt yêu cầu đánh giá lại","8. Lãnh đạo ban chuyên môn phê duyệt / Từ chối yêu cầu đánh giá lại","9. Lãnh đạo Văn phòng tiếp nhận yêu cầu đánh giá lại","10. Chuyên viên Văn phòng cập nhật thông tin đánh giá lại"],"tags":["Văn phòng"],"complexity":"complex","transactions":10,"necessity":"B"},
{"sort":168,"code":"VP-IX","parent":null,"kind":"group","title":"Phân hệ thu hồi","actor":"","flow":[],"tags":["Văn phòng"],"complexity":null,"transactions":null,"necessity":"B"},
{"sort":169,"code":"UC-145","parent":"VP-IX","kind":"usecase","title":"Quản lý thu hồi","actor":"Người sử dụng","flow":["1. Chuyên viên ban chuyên môn thêm mới thu hồi trên giao diện. Hệ thống lưu thông tin thu hồi được thêm mới","2. Chuyên viên ban chuyên môn thực hiện chỉnh sửa thu hồi. Hệ thống lưu thông tin thu hồi do người dùng chỉnh sửa","3. Chuyên viên ban chuyên môn tìm kiếm thu hồi. Hệ thống tìm kiếm và trả kết quả cho người dùng","4. Chuyên viên ban chuyên môn xem chi tiết thu hồi. Hệ thống hiển thị chi tiết thu hồi","5. Chuyên viên ban chuyên môn xuất dữ liệu thu hồi ra file excel. Hệ thống thực hiện xuất theo yêu cầu","6. Chuyên viên ban chuyên môn gửi trình phê duyệt yêu cầu thu hồi","7. Lãnh đạo ban chuyên môn phê duyệt / Từ chối yêu cầu thu hồi","8. Lãnh đạo văn phòng tiếp nhận yêu cầu thu hồi","9. Chuyên viên văn phòng cập nhật thông tin sau thu hồi"],"tags":["Văn phòng"],"complexity":"complex","transactions":9,"necessity":"B"},
{"sort":170,"code":"UC-146","parent":"VP-IX","kind":"usecase","title":"Tổng hợp thu hồi","actor":"Chuyên viên Văn phòng","flow":["1. Chuyên viên Văn phòng xem tổng hợp danh sách vật tư thiết bị thu hồi tái sử dụng","2. Chuyên viên Văn phòng xem tổng hợp danh sách vật tư thiết bị cần loại khỏi danh mục quản lý"],"tags":["Văn phòng"],"complexity":"simple","transactions":2,"necessity":"B"},
{"sort":171,"code":"VP-X","parent":null,"kind":"group","title":"Thống kê, báo cáo","actor":"","flow":[],"tags":["Văn phòng"],"complexity":null,"transactions":null,"necessity":"B"},
{"sort":172,"code":"VP-X.1","parent":"VP-X","kind":"group","title":"Dashboard","actor":"","flow":[],"tags":["Văn phòng"],"complexity":null,"transactions":null,"necessity":"B"},
{"sort":173,"code":"UC-147","parent":"VP-X.1","kind":"usecase","title":"Dashboard theo dõi tính hình cấp phát","actor":"Người sử dụng","flow":["1. Người sử dụng xem Dashboard theo dõi tính hình cấp phát . Hệ thống hiển thị thông tin chi tiết Dashboard theo dõi tính hình cấp phát","2. Người sử dụng nhập các tiêu chí lọc về d theo dõi tính hình cấp phát . Hệ thống truy vấn thông tin trong CSDL và hiển thị kết quả Dashboard theo dõi tính hình cấp phát theo tiêu chí lọc"],"tags":["Văn phòng"],"complexity":"simple","transactions":2,"necessity":"B"},
{"sort":174,"code":"VP-X.2","parent":"VP-X","kind":"group","title":"Báo cáo","actor":"","flow":[],"tags":["Văn phòng"],"complexity":null,"transactions":null,"necessity":"B"},
{"sort":175,"code":"UC-148","parent":"VP-X.2","kind":"usecase","title":"Báo cáo kiểm kê tài sản","actor":"Chuyên viên Văn phòng","flow":["1. Chuyên viên Văn phòng xem Báo cáo kiểm kê tài sản. Hệ thống hiển thị thông tin chi tiết Báo cáo kiểm kê tài sản","2. Chuyên viên Văn phòng nhập các tiêu chí lọc về kiểm kê tài sản. Hệ thống truy vấn thông tin trong CSDL và hiển thị kết quả Báo cáo kiểm kê tài sản theo tiêu chí lọc"],"tags":["Văn phòng"],"complexity":"simple","transactions":2,"necessity":"B"},
{"sort":176,"code":"UC-149","parent":"VP-X.2","kind":"usecase","title":"Báo cáo hiện trạng sử dụng","actor":"Chuyên viên Văn phòng","flow":["1. Chuyên viên Văn phòng xem Báo cáo hiện trạng sử dụng. Hệ thống hiển thị thông tin chi tiết Báo cáo hiện trạng sử dụng","2. Chuyên viên Văn phòng nhập các tiêu chí lọc về hiện trạng sử dụng. Hệ thống truy vấn thông tin trong CSDL và hiển thị kết quả Báo cáo hiện trạng sử dụng theo tiêu chí lọc"],"tags":["Văn phòng"],"complexity":"simple","transactions":2,"necessity":"B"},
{"sort":177,"code":"UC-150","parent":"VP-X.2","kind":"usecase","title":"Báo cáo bảo trì, bảo dưỡng","actor":"Chuyên viên Văn phòng","flow":["1. Chuyên viên Văn phòng xem Báo cáo bảo trì, bảo dưỡng. Hệ thống hiển thị thông tin chi tiết Báo cáo bảo trì, bảo dưỡng","2. Chuyên viên Văn phòng nhập các tiêu chí lọc về bảo trì, bảo dưỡng. Hệ thống truy vấn thông tin trong CSDL và hiển thị kết quả Báo cáo bảo trì, bảo dưỡng theo tiêu chí lọc"],"tags":["Văn phòng"],"complexity":"simple","transactions":2,"necessity":"B"},
{"sort":178,"code":"VP-XI","parent":null,"kind":"group","title":"Hồ sơ vật tư, thiết bị Văn phòng","actor":"","flow":[],"tags":["Văn phòng"],"complexity":null,"transactions":null,"necessity":"B"},
{"sort":179,"code":"UC-151","parent":"VP-XI","kind":"usecase","title":"Tìm kiếm và xem danh sách hồ sơ vật tư, thiết bị Văn phòng","actor":"Người dùng","flow":["1. Người dùng tìm kiếm và xem danh sách hồ sơ vật tư, thiết bị. Hệ thống hiển thị danh sách hồ sơ vật tư thiết bị theo điều kiện tìm kiếm"],"tags":["Văn phòng"],"complexity":"simple","transactions":1,"necessity":"B"},
{"sort":180,"code":"UC-152","parent":"VP-XI","kind":"usecase","title":"Chỉnh sửa thông tin Hồ sơ vật tư, thiết bị Văn phòng","actor":"Người dùng","flow":["1. Người dùng chỉnh sửa thông tin một vật tư, thiết bị. Hệ thống lưu thông tin chỉnh sửa của vật tư, thiết bị"],"tags":["Văn phòng"],"complexity":"simple","transactions":1,"necessity":"B"},
{"sort":181,"code":"UC-153","parent":"VP-XI","kind":"usecase","title":"Xem thông tin Hồ sơ vật tư, thiết bị - thông tin chung","actor":"Người dùng","flow":["1. Người dùng xem chi tiết thông tin chung của một vật tư, thiết bị. Hệ thống hiển thị chi tiết về thông tin chung của vật tư, thiết bị"],"tags":["Văn phòng"],"complexity":"simple","transactions":1,"necessity":"B"},
{"sort":182,"code":"UC-154","parent":"VP-XI","kind":"usecase","title":"Xem thông tin Hồ sơ vật tư, thiết bị - Thông tin chi tiết","actor":"Người dùng","flow":["1. Người dùng xem chi tiết thông tin chi tiếtcủa một vật tư, thiết bị. Hệ thống hiển thị thông tin chi tiết của vật tư, thiết bị"],"tags":["Văn phòng"],"complexity":"simple","transactions":1,"necessity":"B"},
{"sort":183,"code":"UC-155","parent":"VP-XI","kind":"usecase","title":"Xem thông tin Hồ sơ vật tư, thiết bị - Lịch sử điều chuyển","actor":"Người dùng","flow":["1. Người dùng xem chi tiết thông tin lịch sử điều chuyển của một vật tư, thiết bị. Hệ thống hiển thị chi tiết về lịch sử điều chuyển của vật tư, thiết bị"],"tags":["Văn phòng"],"complexity":"simple","transactions":1,"necessity":"B"},
{"sort":184,"code":"UC-156","parent":"VP-XI","kind":"usecase","title":"Xem thông tin Hồ sơ vật tư, thiết bị - thông tin vận hành","actor":"Người dùng","flow":["1. Người dùng tìm kiếm thông tin vận hành của vật tư, thiết bị. Hệ thống tìm kiếm và trả kết quả cho người dùng"],"tags":["Văn phòng"],"complexity":"simple","transactions":1,"necessity":"B"}]
$json$::jsonb)
        as x(sort integer, code text, parent text, kind text, title text, actor text, flow jsonb, tags jsonb,
             complexity text, transactions integer, necessity text)
     order by sort
  loop
    v_parent := null;
    if r.parent is not null then
      select id into v_parent from public.use_cases where project_id = v_project and code = r.parent;
      if v_parent is null then
        raise exception 'Không tìm thấy use case cha % của %', r.parent, r.code;
      end if;
    end if;

    insert into public.use_cases
      (project_id, parent_id, code, title, actor, main_flow, kind, tags, complexity, transactions, necessity)
    values
      (v_project, v_parent, r.code, r.title, coalesce(r.actor, ''),
       array(select jsonb_array_elements_text(r.flow)),
       r.kind, array(select jsonb_array_elements_text(r.tags)), r.complexity, r.transactions, coalesce(r.necessity, 'B'))
    on conflict (project_id, code) do update
      set parent_id = excluded.parent_id,
          title = excluded.title,
          actor = excluded.actor,
          main_flow = excluded.main_flow,
          kind = excluded.kind,
          tags = excluded.tags,
          complexity = excluded.complexity,
          transactions = excluded.transactions,
          necessity = excluded.necessity
    returning (xmax = 0) into v_new;

    if v_new then n_new := n_new + 1; else n_upd := n_upd + 1; end if;
  end loop;

  raise notice 'Nhập xong: % use case/nhóm mới, % cập nhật.', n_new, n_upd;
end
$import$;

-- Kiểm tra nhanh: kỳ vọng 13 nhóm và 23 use case.
select kind, count(*) as so_luong
  from public.use_cases
 where project_id = (select id from public.projects where code = 'GPDN_DNMB_EVNNPC_QTVT_251004')
   and code in ('VP-I', 'UC-134', 'VP-II', 'UC-135', 'UC-136', 'VP-III', 'UC-137', 'VP-IV', 'UC-138', 'VP-V', 'UC-139', 'VP-VI', 'UC-140', 'UC-141', 'VP-VII', 'UC-142', 'UC-143', 'VP-VIII', 'UC-144', 'VP-IX', 'UC-145', 'UC-146', 'VP-X', 'VP-X.1', 'UC-147', 'VP-X.2', 'UC-148', 'UC-149', 'UC-150', 'VP-XI', 'UC-151', 'UC-152', 'UC-153', 'UC-154', 'UC-155', 'UC-156')
 group by kind
 order by kind;
