-- Nhập danh sách Use Case dự án GPDN_DNMB_EVNNPC_QTVT_251004 - phần Kho dữ liệu
-- Nguồn: Danh sách chức năng điều chỉnh BCC Vật tư_0508.xlsx (sheet UC sau điều chỉnh final)
-- Gồm 6 module/nhóm (kind = group) và 28 use case (kind = usecase), cây tối đa 3 cấp.
-- Sinh tự động bởi scripts/gen-usecase-import.py - đừng sửa tay, hãy sửa Excel rồi sinh lại.
--
-- Chạy SAU migration 0009_usecase_attributes.sql, trong Supabase SQL Editor.
-- An toàn khi chạy lại: khớp theo (dự án, mã); chỉ cập nhật tên/tác nhân/luồng/nhãn/độ phức tạp/transaction,
-- KHÔNG ghi đè trạng thái, tiến độ, người phụ trách, mô tả hay tiêu chí nghiệm thu đã nhập tay.
-- Hoàn tác: chạy qtvt_usecases_rollback.sql.

do $import$
declare
  v_project_code constant text := 'GPDN_DNMB_EVNNPC_QTVT_251004';
  v_project uuid;
  r record;
  v_parent uuid;
  v_new boolean;
  n_new integer := 0;
  n_upd integer := 0;
begin
  select id into v_project from public.projects where code = v_project_code;
  if v_project is null then
    raise exception 'Không tìm thấy dự án có mã %. Kiểm tra lại mã dự án.', v_project_code;
  end if;

  for r in
    select *
      from jsonb_to_recordset($json$[{"sort":185,"code":"KDL-I","parent":null,"kind":"group","title":"Mapping danh mục Vật tư thiết bị","actor":"","flow":[],"tags":["Kho dữ liệu"],"complexity":null,"transactions":null,"necessity":"B"},
{"sort":186,"code":"UC-157","parent":"KDL-I","kind":"usecase","title":"Mapping danh mục vật tư, thiết bị giữa các hệ thống","actor":"Người dùng","flow":["1. Người dùng thực hiện mapping thủ công mã danh mục vật tư, thiết bị giữa các hệ thống trên kho dữ liệu. Kho dữ liệu tạo một mã danh mục vật tư, thiết bị mới để mapping mã danh mục vật tư, thiết bị giữa các hệ thống, lưu kết quả mapping và tên trên Kho dữ liệu tập trung.","2. Người dùng xem kết quả gợi ý mapping danh mục. Kho dữ liệu hiển thị gợi ý mapping","3. Người dùng thực hiện xác nhận/ không xác nhận kết quả mapping theo gợi ý. Kho dữ liệu lưu kết quả mapping theo sự lựa chọn của người dùng","4. Người dùng import file mapping danh mục vật tư, thiết bị giữa các hệ thống. Kho dữ liệu đọc file import vào lưu kết quả mapping","5. Người dùng chỉnh sửa kết quả mapping danh mục vật tư, thiết bị giữa các hệ thống. Kho dữ liệu lưu kết quả chỉnh sửa mapping","6. Người dùng xóa kết quả mapping danh mục vật tư, thiết bị giữa các hệ thống. Kho dữ liệu xóa kết quả mapping","7. Người dùng tìm kiếm danh mục vật tư, thiết bị giữa các hệ thống đã được mapping. Kho dữ liệu hiển thị kết quả tìm kiếm cho người dùng"],"tags":["Kho dữ liệu"],"complexity":"medium","transactions":7,"necessity":"B"},
{"sort":187,"code":"UC-158","parent":"KDL-I","kind":"usecase","title":"Mapping danh mục nhà cung cấp giữa các hệ thống","actor":"Người dùng","flow":["1. Người dùng thực hiện mapping thủ công mã nhà cung cấp giữa các hệ thống trên kho dữ liệu. Kho dữ liệu lưu kết quả mapping của người dùng","2. Người dùng xem kết quả gợi ý mapping danh mục. Kho dữ liệu hiển thị gợi ý mapping","3. Người dùng thực hiện xác nhận/ không xác nhận kết quả mapping theo gợi ý. Kho dữ liệu lưu kết quả mapping theo sự lựa chọn của người dùng","4. Người dùng import file mapping danh mục nhà cung cấp giữa các hệ thống. Kho dữ liệu đọc file import vào lưu kết quả mapping","5. Người dùng chỉnh sửa kết quả mapping danh mục nhà cung cấp giữa các hệ thống. Kho dữ liệu lưu kết quả chỉnh sửa mapping","6. Người dùng xóa kết quả mapping danh mục nhà cung cấp giữa các hệ thống. Kho dữ liệu xóa kết quả mapping","7. Người dùng tìm kiếm danh mục nhà cung cấp giữa các hệ thống đã được mapping. Kho dữ liệu hiển thị kết quả tìm kiếm cho người dùng"],"tags":["Kho dữ liệu"],"complexity":"medium","transactions":7,"necessity":"B"},
{"sort":188,"code":"UC-159","parent":"KDL-I","kind":"usecase","title":"Mapping danh mục nhà sản xuất giữa các hệ thống","actor":"Người dùng","flow":["1. Người dùng thực hiện mapping thủ công danh mục nhà sản xuất giữa các hệ thống. Kho dữ liệu lưu kết quả mapping của người dùng","2. Người dùng xem kết quả gợi ý mapping danh mục. Kho dữ liệu hiển thị gợi ý mapping","3. Người dùng thực hiện xác nhận/ không xác nhận kết quả mapping theo gợi ý. Kho dữ liệu lưu kết quả mapping theo sự lựa chọn của người dùng","4. Người dùng import file mapping danh mục nhà sản xuất giữa các hệ thống. Kho dữ liệu đọc file import vào lưu kết quả mapping","5. Người dùng chỉnh sửa kết quả mapping danh mục nhà sản xuất giữa các hệ thống. Kho dữ liệu lưu kết quả chỉnh sửa mapping","6. Người dùng xóa kết quả mapping danh mục nhà sản xuất giữa các hệ thống. Kho dữ liệu xóa kết quả mapping","7. Người dùng tìm kiếm danh mục nhà sản xuất giữa các hệ thống đã được mapping.Kho dữ liệu hiển thị kết quả tìm kiếm cho người dùng"],"tags":["Kho dữ liệu"],"complexity":"medium","transactions":7,"necessity":"B"},
{"sort":189,"code":"KDL-II","parent":null,"kind":"group","title":"Cảnh báo mapping","actor":"","flow":[],"tags":["Kho dữ liệu"],"complexity":null,"transactions":null,"necessity":"B"},
{"sort":190,"code":"UC-160","parent":"KDL-II","kind":"usecase","title":"Cảnh báo danh mục nhóm VTTB chưa có mapping","actor":"Người dùng","flow":["1. Người dùng xem danh mục nhóm VTTB chưa có mapping có phân trang. Hệ thống thực hiện chuyển trang theo yêu cầu"],"tags":["Kho dữ liệu"],"complexity":"simple","transactions":1,"necessity":"B"},
{"sort":191,"code":"UC-161","parent":"KDL-II","kind":"usecase","title":"Cảnh báo danh mục nhà cung cấp chưa có mapping","actor":"Người dùng","flow":["1. Người dùng xem danh mục nhà cung cấp chưa có mapping có phân trang. Hệ thống thực hiện chuyển trang theo yêu cầu"],"tags":["Kho dữ liệu"],"complexity":"simple","transactions":1,"necessity":"B"},
{"sort":192,"code":"UC-162","parent":"KDL-II","kind":"usecase","title":"Cảnh báo danh mục nhà sản xuất chưa có mapping","actor":"Người dùng","flow":["1. Người dùng xem danh mục nhà sản xuất chưa có mapping có phân trang. Hệ thống thực hiện chuyển trang theo yêu cầu"],"tags":["Kho dữ liệu"],"complexity":"simple","transactions":1,"necessity":"B"},
{"sort":193,"code":"KDL-III","parent":null,"kind":"group","title":"Báo cáo và Dashboard quản lý thông tin Vật tư, thiết bị","actor":"","flow":[],"tags":["Kho dữ liệu"],"complexity":null,"transactions":null,"necessity":"B"},
{"sort":194,"code":"KDL-III.1","parent":"KDL-III","kind":"group","title":"Báo cáo","actor":"","flow":[],"tags":["Kho dữ liệu"],"complexity":null,"transactions":null,"necessity":"B"},
{"sort":195,"code":"UC-163","parent":"KDL-III.1","kind":"usecase","title":"Báo cáo chi tiết trạng thái QR Code","actor":"Người dùng","flow":["1. Người dùng xem Báo cáo chi tiết trạng thái QR Code. Hệ thống hiển thị thông tin chi tiết Báo cáo chi tiết trạng thái QR Code","2. Người dùng nhập các tiêu chí lọc về chi tiết trạng thái QR Code. Hệ thống truy vấn thông tin trong CSDL và hiển thị kết quả Báo cáo chi tiết trạng thái QR Code theo tiêu chí lọc"],"tags":["Kho dữ liệu"],"complexity":"simple","transactions":2,"necessity":"B"},
{"sort":196,"code":"UC-164","parent":"KDL-III.1","kind":"usecase","title":"Báo cáo theo dõi tồn kho định danh","actor":"Người dùng","flow":["1. Người dùng xem Báo cáo theo dõi tồn kho định danh. Hệ thống hiển thị thông tin chi tiết Báo cáo theo dõi tồn kho định danh","2. Người dùng nhập các tiêu chí lọc về theo dõi tồn kho định danh. Hệ thống truy vấn thông tin trong CSDL và hiển thị kết quả Báo cáo theo dõi tồn kho định danh theo tiêu chí lọc"],"tags":["Kho dữ liệu"],"complexity":"simple","transactions":2,"necessity":"B"},
{"sort":197,"code":"UC-165","parent":"KDL-III.1","kind":"usecase","title":"Báo cáo theo dõi kế hoạch định danh","actor":"Người dùng","flow":["1. Người dùng xem Báo cáo theo dõi kế hoạch định danh. Hệ thống hiển thị thông tin chi tiết Báo cáo theo dõi kế hoạch định danh","2. Người dùng nhập các tiêu chí lọc về theo dõi kế hoạch định danh. Hệ thống truy vấn thông tin trong CSDL và hiển thị kết quả Báo cáo theo dõi kế hoạch định danh theo tiêu chí lọc"],"tags":["Kho dữ liệu"],"complexity":"simple","transactions":2,"necessity":"B"},
{"sort":198,"code":"UC-166","parent":"KDL-III.1","kind":"usecase","title":"Báo cáo theo dõi tình hình mua sắm của các đơn vị trong TCT","actor":"Người dùng","flow":["1. Người dùng xem Báo cáo theo dõi tình hình mua sắm của các đơn vị trong TCT. Hệ thống hiển thị thông tin chi tiết Báo cáo theo dõi tình hình mua sắm của các đơn vị trong TCT","2. Người dùng nhập các tiêu chí lọc về theo dõi tình hình mua sắm của các đơn vị trong TCT. Hệ thống truy vấn thông tin trong CSDL và hiển thị kết quả Báo cáo theo dõi tình hình mua sắm của các đơn vị trong TCT theo tiêu chí lọc"],"tags":["Kho dữ liệu"],"complexity":"simple","transactions":2,"necessity":"B"},
{"sort":199,"code":"UC-167","parent":"KDL-III.1","kind":"usecase","title":"Báo cáo đánh giá mua sắm theo thời gian","actor":"Người dùng","flow":["1. Người dùng xem Báo cáo đánh giá mua sắm theo thời gian. Hệ thống hiển thị thông tin chi tiết Báo cáo đánh giá mua sắm theo thời gian","2. Người dùng nhập các tiêu chí lọc về đánh giá mua sắm theo thời gian. Hệ thống truy vấn thông tin trong CSDL và hiển thị kết quả Báo cáo đánh giá mua sắm theo thời gian theo tiêu chí lọc"],"tags":["Kho dữ liệu"],"complexity":"simple","transactions":2,"necessity":"B"},
{"sort":200,"code":"UC-168","parent":"KDL-III.1","kind":"usecase","title":"Báo cáo xu hướng nhu cầu mua sắm","actor":"Người dùng","flow":["1. Người dùng xem Báo cáo xu hướng nhu cầu mua sắm. Hệ thống hiển thị thông tin chi tiết Báo cáo xu hướng nhu cầu mua sắm","2. Người dùng nhập các tiêu chí lọc về xu hướng nhu cầu mua sắm. Hệ thống truy vấn thông tin trong CSDL và hiển thị kết quả Báo cáo xu hướng nhu cầu mua sắm theo tiêu chí lọc"],"tags":["Kho dữ liệu"],"complexity":"simple","transactions":2,"necessity":"B"},
{"sort":201,"code":"UC-169","parent":"KDL-III.1","kind":"usecase","title":"Báo cáo tổng hợp số lượng VTTB theo vòng đời","actor":"Người dùng","flow":["1. Người dùng xem Báo cáo tổng hợp số lượng VTTB theo vòng đời. Hệ thống hiển thị thông tin chi tiết Báo cáo tổng hợp số lượng VTTB theo vòng đời","2. Người dùng nhập các tiêu chí lọc về tổng hợp số lượng VTTB theo vòng đời. Hệ thống truy vấn thông tin trong CSDL và hiển thị kết quả Báo cáo tổng hợp số lượng VTTB theo vòng đời theo tiêu chí lọc"],"tags":["Kho dữ liệu"],"complexity":"simple","transactions":2,"necessity":"B"},
{"sort":202,"code":"UC-170","parent":"KDL-III.1","kind":"usecase","title":"Báo cáo tổng hợp thời gian tồn kho","actor":"Người dùng","flow":["1. Người dùng xem Báo cáo tổng hợp thời gian tồn kho. Hệ thống hiển thị thông tin chi tiết Báo cáo tổng hợp thời gian tồn kho","2. Người dùng nhập các tiêu chí lọc về tổng hợp thời gian tồn kho. Hệ thống truy vấn thông tin trong CSDL và hiển thị kết quả Báo cáo tổng hợp thời gian tồn kho theo tiêu chí lọc"],"tags":["Kho dữ liệu"],"complexity":"simple","transactions":2,"necessity":"B"},
{"sort":203,"code":"UC-171","parent":"KDL-III.1","kind":"usecase","title":"Báo cáo tổng hợp thời gian vận hành của VTTB","actor":"Người dùng","flow":["1. Người dùng xem Báo cáo tổng hợp thời gian vận hành của VTTB. Hệ thống hiển thị thông tin chi tiết Báo cáo tổng hợp thời gian vận hành của VTTB","2. Người dùng nhập các tiêu chí lọc về tổng hợp thời gian vận hành của VTTB. Hệ thống truy vấn thông tin trong CSDL và hiển thị kết quả Báo cáo tổng hợp thời gian vận hành của VTTB theo tiêu chí lọc"],"tags":["Kho dữ liệu"],"complexity":"simple","transactions":2,"necessity":"B"},
{"sort":204,"code":"UC-172","parent":"KDL-III.1","kind":"usecase","title":"Báo cáo tổng số VTTB trên lưới","actor":"Người dùng","flow":["1. Người dùng xem Báo cáo tổng số VTTB trên lưới. Hệ thống hiển thị thông tin chi tiết Báo cáo tổng số VTTB trên lưới","2. Người dùng nhập các tiêu chí lọc về tổng số VTTB trên lưới. Hệ thống truy vấn thông tin trong CSDL và hiển thị kết quả Báo cáo tổng số VTTB trên lưới theo tiêu chí lọc"],"tags":["Kho dữ liệu"],"complexity":"simple","transactions":2,"necessity":"B"},
{"sort":205,"code":"UC-173","parent":"KDL-III.1","kind":"usecase","title":"Báo cáo vật tư đã xuất kho nhưng chưa được treo tháo","actor":"Người dùng","flow":["1. Người dùng xem Báo cáo vật tư đã xuất kho nhưng chưa được treo tháo. Hệ thống hiển thị thông tin chi tiết Báo cáo vật tư đã xuất kho nhưng chưa được treo tháo","2. Người dùng nhập các tiêu chí lọc về vật tư đã xuất kho nhưng chưa được treo tháo. Hệ thống truy vấn thông tin trong CSDL và hiển thị kết quả Báo cáo vật tư đã xuất kho nhưng chưa được treo tháo theo tiêu chí lọc"],"tags":["Kho dữ liệu"],"complexity":"simple","transactions":2,"necessity":"B"},
{"sort":206,"code":"UC-174","parent":"KDL-III.1","kind":"usecase","title":"Báo cáo tổng hợp thiết bị đã nhập trên ERP nhưng quá hạn chưa được định danh","actor":"Người dùng","flow":["1. Người dùng xem Báo cáo tổng hợp thiết bị đã nhập trên ERP nhưng quá hạn chưa được định danh. Hệ thống hiển thị thông tin chi tiết Báo cáo tổng hợp thiết bị đã nhập trên ERP nhưng quá hạn chưa được định danh","2. Người dùng nhập các tiêu chí lọc về tổng hợp thiết bị đã nhập trên ERP nhưng quá hạn chưa được định danh. Hệ thống truy vấn thông tin trong CSDL và hiển thị kết quả Báo cáo tổng hợp thiết bị đã nhập trên ERP nhưng quá hạn chưa được định danh theo tiêu chí lọc"],"tags":["Kho dữ liệu"],"complexity":"simple","transactions":2,"necessity":"B"},
{"sort":207,"code":"UC-175","parent":"KDL-III.1","kind":"usecase","title":"Báo cáo thiết bị xuống lưới nhưng không nhập kho","actor":"Người dùng","flow":["1. Người dùng xem Báo cáo thiết bị xuống lưới nhưng không nhập kho. Hệ thống hiển thị thông tin chi tiết Báo cáo thiết bị xuống lưới nhưng không nhập kho","2. Người dùng nhập các tiêu chí lọc về thiết bị xuống lưới nhưng không nhập kho. Hệ thống truy vấn thông tin trong CSDL và hiển thị kết quả Báo cáo thiết bị xuống lưới nhưng không nhập kho theo tiêu chí lọc"],"tags":["Kho dữ liệu"],"complexity":"simple","transactions":2,"necessity":"B"},
{"sort":208,"code":"KDL-III.2","parent":"KDL-III","kind":"group","title":"Dashboard quản trị","actor":"","flow":[],"tags":["Kho dữ liệu"],"complexity":null,"transactions":null,"necessity":"B"},
{"sort":209,"code":"UC-176","parent":"KDL-III.2","kind":"usecase","title":"Đánh giá chất lượng vật tư thiết bị","actor":"Người dùng","flow":["1. Người dùng xem Đánh giá chất lượng vật tư thiết bị. Hệ thống hiển thị thông tin chi tiết Đánh giá chất lượng vật tư thiết bị","2. Người dùng nhập các tiêu chí lọc về chất lượng vật tư thiết bị. Hệ thống truy vấn thông tin trong CSDL và hiển thị kết quả Đánh giá chất lượng vật tư thiết bị theo tiêu chí lọc"],"tags":["Kho dữ liệu"],"complexity":"simple","transactions":2,"necessity":"B"},
{"sort":210,"code":"UC-177","parent":"KDL-III.2","kind":"usecase","title":"Danh sách nhà sản xuất có tỷ lệ lỗi vật tư thiết bị lớn nhất","actor":"Người dùng","flow":["1. Người dùng xem Danh sách nhà sản xuất có tỷ lệ lỗi vật tư thiết bị lớn nhất. Hệ thống hiển thị thông tin chi tiết Danh sách nhà sản xuất có tỷ lệ lỗi vật tư thiết bị lớn nhất","2. Người dùng nhập các tiêu chí lọc về h nhà sản xuất có tỷ lệ lỗi vật tư thiết bị lớn nhất. Hệ thống truy vấn thông tin trong CSDL và hiển thị kết quả Danh sách nhà sản xuất có tỷ lệ lỗi vật tư thiết bị lớn nhất theo tiêu chí lọc"],"tags":["Kho dữ liệu"],"complexity":"simple","transactions":2,"necessity":"B"},
{"sort":211,"code":"UC-178","parent":"KDL-III.2","kind":"usecase","title":"Danh sách nhà cung cấp có tỷ lệ lỗi vật tư thiết bị lớn nhất","actor":"Người dùng","flow":["1. Người dùng xem Danh sách nhà cung cấp có tỷ lệ lỗi vật tư thiết bị lớn nhất. Hệ thống hiển thị thông tin chi tiết Danh sách nhà cung cấp có tỷ lệ lỗi vật tư thiết bị lớn nhất","2. Người dùng nhập các tiêu chí lọc về h nhà cung cấp có tỷ lệ lỗi vật tư thiết bị lớn nhất. Hệ thống truy vấn thông tin trong CSDL và hiển thị kết quả Danh sách nhà cung cấp có tỷ lệ lỗi vật tư thiết bị lớn nhất theo tiêu chí lọc"],"tags":["Kho dữ liệu"],"complexity":"simple","transactions":2,"necessity":"B"},
{"sort":212,"code":"KDL-IV","parent":null,"kind":"group","title":"Tổng hợp và xử lý dữ liệu tại Kho dữ liệu","actor":"","flow":[],"tags":["Kho dữ liệu"],"complexity":null,"transactions":null,"necessity":"B"},
{"sort":213,"code":"UC-179","parent":"KDL-IV","kind":"usecase","title":"Tổng hợp và xử lý dữ liệu kế hoạch định danh","actor":"Kho dữ liệu","flow":["1. Kho dữ liệu cấu hình tham số cho tiến trình về làm sạch, ánh xạ, tổng hợp dữ liệu kế hoạch định danh . Hệ thống hiển thị giao diện để cấu hình các tham số cho tiến trình làm sạch, ánh xạ, tổng hợpdữ liệu kế hoạch định danh","2. Kho dữ liệu bật/ tắt tiến trình về làm sạch, ánh xạ, tổng hợp dữ liệu kế hoạch định danh . Hệ thống chạy tiến trình về làm sạch, ánh xạ, tổng hợp và lưu kết quả vào vùng dữ liệu tổng hợp và CSDL chủ đề về KTVH","3. Kho dữ liệu xem kết quả chạy tiến trình về làm sạch, ánh xạ, tổng hợp dữ liệu kế hoạch định danh . Hệ thống hiển thị kết quả của tiến trình làm sạch, ánh xạ, tổng hợp dữ liệu kế hoạch định danh","4. Kho dữ liệu theo dõi thông tin log của tiến trình làm sạch, ánh xạ, tổng hợp dữ liệu kế hoạch định danh . Hệ thống hiển thị màn hình quản lý danh sách log của tiến trình làm sạch, ánh xạ, tổng hợp dữ liệu kế hoạch định danh","5. Kho dữ liệu xem chi tiết thông tin log của tiến trình làm sạch, ánh xạ, tổng hợp dữ liệu kế hoạch định danh . Hệ thống hiển thị thông tin chi tiết log của tiến trình làm sạch, ánh xạ, tổng hợp dữ liệu kế hoạch định danh"],"tags":["Kho dữ liệu"],"complexity":"medium","transactions":5,"necessity":"B"},
{"sort":214,"code":"UC-180","parent":"KDL-IV","kind":"usecase","title":"Tổng hợp và xử lý dữ liệu định danh VTTB","actor":"Kho dữ liệu","flow":["1. Kho dữ liệu cấu hình tham số cho tiến trình về làm sạch, ánh xạ, tổng hợp dữ liệu định danh VTTB. Hệ thống hiển thị giao diện để cấu hình các tham số cho tiến trình làm sạch, ánh xạ, tổng hợpdữ liệu định danh VTTB","2. Kho dữ liệu bật/ tắt tiến trình về làm sạch, ánh xạ, tổng hợp dữ liệu định danh VTTB. Hệ thống chạy tiến trình về làm sạch, ánh xạ, tổng hợp và lưu kết quả vào vùng dữ liệu tổng hợp và CSDL chủ đề về KTVH","3. Kho dữ liệu xem kết quả chạy tiến trình về làm sạch, ánh xạ, tổng hợp dữ liệu định danh VTTB. Hệ thống hiển thị kết quả của tiến trình làm sạch, ánh xạ, tổng hợp dữ liệu định danh VTTB","4. Kho dữ liệu theo dõi thông tin log của tiến trình làm sạch, ánh xạ, tổng hợp dữ liệu định danh VTTB. Hệ thống hiển thị màn hình quản lý danh sách log của tiến trình làm sạch, ánh xạ, tổng hợp dữ liệu định danh VTTB","5. Kho dữ liệu xem chi tiết thông tin log của tiến trình làm sạch, ánh xạ, tổng hợp dữ liệu định danh VTTB. Hệ thống hiển thị thông tin chi tiết log của tiến trình làm sạch, ánh xạ, tổng hợp dữ liệu định danh VTTB"],"tags":["Kho dữ liệu"],"complexity":"medium","transactions":5,"necessity":"B"},
{"sort":215,"code":"UC-181","parent":"KDL-IV","kind":"usecase","title":"Tổng hợp dữ liệu thời gian tồn kho","actor":"Kho dữ liệu","flow":["1. Hệ thống yêu cầu kết nối đến Kho dữ liệu. Kho dữ liệu phản hồi thông tin yêu cầu xác thực.","2. Hệ thống gửi thông tin xác thực. Kho dữ liệu xác thực thông tin và phản hồi lại kết quả kết nối: cho phép kết nối nếu xác thực thành công, từ chối mở kết nối nếu không xác thực thành công","3. Hệ thống Tổng hợp dữ liệu thời gian tồn kho. Kho dữ liệu xử lý dữ liệu thời gian tồn kho","4. Hệ thống gửi yêu cầu đóng kết nối tới Kho dữ liệu. Kho dữ liệu thực hiện đóng kết nối và lưu liệu thời gian tồn kho vào CSDL"],"tags":["Kho dữ liệu"],"complexity":"medium","transactions":4,"necessity":"B"},
{"sort":216,"code":"UC-182","parent":"KDL-IV","kind":"usecase","title":"Tổng hợp dữ liệu VTTB trên lưới","actor":"Kho dữ liệu","flow":["1. Hệ thống yêu cầu kết nối đến Kho dữ liệu. Kho dữ liệu phản hồi thông tin yêu cầu xác thực.","2. Hệ thống gửi thông tin xác thực. Kho dữ liệu xác thực thông tin và phản hồi lại kết quả kết nối: cho phép kết nối nếu xác thực thành công, từ chối mở kết nối nếu không xác thực thành công","3. Hệ thống Tổng hợp dữ liệu VTTB trên lưới. Kho dữ liệu xử lý dữ liệu VTTB trên lưới","4. Hệ thống gửi yêu cầu đóng kết nối tới Kho dữ liệu. Kho dữ liệu thực hiện đóng kết nối và lưu liệu VTTB trên lưới vào CSDL"],"tags":["Kho dữ liệu"],"complexity":"medium","transactions":4,"necessity":"B"},
{"sort":217,"code":"UC-183","parent":"KDL-IV","kind":"usecase","title":"Tổng hợp và xử lý dữ liệu sự cố theo NCC, NSX, nguyên nhân","actor":"Kho dữ liệu","flow":["1. Kho dữ liệu cấu hình tham số cho tiến trình về làm sạch, ánh xạ, tổng hợp dữ liệu sự cố theo NCC, NSX, nguyên nhân. Hệ thống hiển thị giao diện để cấu hình các tham số cho tiến trình làm sạch, ánh xạ, tổng hợpdữ liệu sự cố theo NCC, NSX, nguyên nhân","2. Kho dữ liệu bật/ tắt tiến trình về làm sạch, ánh xạ, tổng hợp dữ liệu sự cố theo NCC, NSX, nguyên nhân. Hệ thống chạy tiến trình về làm sạch, ánh xạ, tổng hợp và lưu kết quả vào vùng dữ liệu tổng hợp và CSDL chủ đề về KTVH","3. Kho dữ liệu xem kết quả chạy tiến trình về làm sạch, ánh xạ, tổng hợp dữ liệu sự cố theo NCC, NSX, nguyên nhân. Hệ thống hiển thị kết quả của tiến trình làm sạch, ánh xạ, tổng hợp dữ liệu sự cố theo NCC, NSX, nguyên nhân","4. Kho dữ liệu theo dõi thông tin log của tiến trình làm sạch, ánh xạ, tổng hợp dữ liệu sự cố theo NCC, NSX, nguyên nhân. Hệ thống hiển thị màn hình quản lý danh sách log của tiến trình làm sạch, ánh xạ, tổng hợp dữ liệu sự cố theo NCC, NSX, nguyên nhân","5. Kho dữ liệu xem chi tiết thông tin log của tiến trình làm sạch, ánh xạ, tổng hợp dữ liệu sự cố theo NCC, NSX, nguyên nhân. Hệ thống hiển thị thông tin chi tiết log của tiến trình làm sạch, ánh xạ, tổng hợp dữ liệu sự cố theo NCC, NSX, nguyên nhân"],"tags":["Kho dữ liệu"],"complexity":"medium","transactions":5,"necessity":"B"},
{"sort":218,"code":"UC-184","parent":"KDL-IV","kind":"usecase","title":"Tổng hợp và xử lý dữ liệu cấp phát, kiểm kê, bảo trì bảo dưỡng vật tư văn phòng","actor":"Kho dữ liệu","flow":["1. Kho dữ liệu cấu hình tham số cho tiến trình về làm sạch, ánh xạ, tổng hợp dữ liệu cấp phát, kiểm kê, bảo trì bảo dưỡng vật tư văn phòng. Hệ thống hiển thị giao diện để cấu hình các tham số cho tiến trình làm sạch, ánh xạ, tổng hợpdữ liệu cấp phát, kiểm kê, bảo trì bảo dưỡng vật tư văn phòng","2. Kho dữ liệu bật/ tắt tiến trình về làm sạch, ánh xạ, tổng hợp dữ liệu cấp phát, kiểm kê, bảo trì bảo dưỡng vật tư văn phòng. Hệ thống chạy tiến trình về làm sạch, ánh xạ, tổng hợp và lưu kết quả vào vùng dữ liệu tổng hợp và CSDL chủ đề về KTVH","3. Kho dữ liệu xem kết quả chạy tiến trình về làm sạch, ánh xạ, tổng hợp dữ liệu cấp phát, kiểm kê, bảo trì bảo dưỡng vật tư văn phòng. Hệ thống hiển thị kết quả của tiến trình làm sạch, ánh xạ, tổng hợp dữ liệu cấp phát, kiểm kê, bảo trì bảo dưỡng vật tư văn phòng","4. Kho dữ liệu theo dõi thông tin log của tiến trình làm sạch, ánh xạ, tổng hợp dữ liệu cấp phát, kiểm kê, bảo trì bảo dưỡng vật tư văn phòng. Hệ thống hiển thị màn hình quản lý danh sách log của tiến trình làm sạch, ánh xạ, tổng hợp dữ liệu cấp phát, kiểm kê, bảo trì bảo dưỡng vật tư văn phòng","5. Kho dữ liệu xem chi tiết thông tin log của tiến trình làm sạch, ánh xạ, tổng hợp dữ liệu cấp phát, kiểm kê, bảo trì bảo dưỡng vật tư văn phòng. Hệ thống hiển thị thông tin chi tiết log của tiến trình làm sạch, ánh xạ, tổng hợp dữ liệu cấp phát, kiểm kê, bảo trì bảo dưỡng vật tư văn phòng"],"tags":["Kho dữ liệu"],"complexity":"medium","transactions":5,"necessity":"B"}]
$json$::jsonb)
        as x(sort integer, code text, parent text, kind text, title text, actor text, flow jsonb, tags jsonb,
             complexity text, transactions integer, necessity text)
     order by sort
  loop
    v_parent := null;
    if r.parent is not null then
      select id into v_parent from public.use_cases where project_id = v_project and code = r.parent;
      if v_parent is null then
        raise exception 'Không tìm thấy use case cha % của %', r.parent, r.code;
      end if;
    end if;

    insert into public.use_cases
      (project_id, parent_id, code, title, actor, main_flow, kind, tags, complexity, transactions, necessity)
    values
      (v_project, v_parent, r.code, r.title, coalesce(r.actor, ''),
       array(select jsonb_array_elements_text(r.flow)),
       r.kind, array(select jsonb_array_elements_text(r.tags)), r.complexity, r.transactions, coalesce(r.necessity, 'B'))
    on conflict (project_id, code) do update
      set parent_id = excluded.parent_id,
          title = excluded.title,
          actor = excluded.actor,
          main_flow = excluded.main_flow,
          kind = excluded.kind,
          tags = excluded.tags,
          complexity = excluded.complexity,
          transactions = excluded.transactions,
          necessity = excluded.necessity
    returning (xmax = 0) into v_new;

    if v_new then n_new := n_new + 1; else n_upd := n_upd + 1; end if;
  end loop;

  raise notice 'Nhập xong: % use case/nhóm mới, % cập nhật.', n_new, n_upd;
end
$import$;

-- Kiểm tra nhanh: kỳ vọng 6 nhóm và 28 use case.
select kind, count(*) as so_luong
  from public.use_cases
 where project_id = (select id from public.projects where code = 'GPDN_DNMB_EVNNPC_QTVT_251004')
   and code in ('KDL-I', 'UC-157', 'UC-158', 'UC-159', 'KDL-II', 'UC-160', 'UC-161', 'UC-162', 'KDL-III', 'KDL-III.1', 'UC-163', 'UC-164', 'UC-165', 'UC-166', 'UC-167', 'UC-168', 'UC-169', 'UC-170', 'UC-171', 'UC-172', 'UC-173', 'UC-174', 'UC-175', 'KDL-III.2', 'UC-176', 'UC-177', 'UC-178', 'KDL-IV', 'UC-179', 'UC-180', 'UC-181', 'UC-182', 'UC-183', 'UC-184')
 group by kind
 order by kind;
